;load cc -> components/core
(defun load-kb (f) (km::load-kb f))
(defun tax (&optional (c 'km::|Thing|)) (km::taxonomy c))
(defun gvl (i sv) ;(rest (gv i sv))
  "getval ret usable list"
  (remove :|seq| (gv i sv))) 
(defun savekb (&optional (fn "tax.kb")) (km::save-kb fn))
;==> ls.cl <==
(load-kb "cc/CLIB-Slot-Group.km")
(load-kb "cc/Interface-Slot.km")
(load-kb "cc/KM-Slot-Group.km")
(load-kb "cc/NL-Slot-Group.km")
(load-kb "cc/Shaken-Slot-Group.km")
(load-kb "cc/Slot.km")
(load-kb "cc/Slot-Query-Viewpoint.km")
(load-kb "cc/Slot-Value-Viewpoint.km")

;==> le.cl <==
(load-kb "cc/Event.km")
(load-kb "cc/Entity.km")
(load-kb "cc/State.km")
(load-kb "cc/object.km")
(load-kb "cc/experiencer.km")
(load-kb "cc/time-during.km")
(load-kb "cc/Time-Interval.km")
(load-kb "cc/Communicate.km")
(load-kb "cc/agent.km")
(load-kb "cc/Agent-Role.km")
(load-kb "cc/Agentive-Relation.km")
(load-kb "cc/recipient.km")
(load-kb "cc/Recipient-Role.km")
(load-kb "cc/Relation.km")
(load-kb "cc/Agentive-Relation.km")
(load-kb "cc/Causal-Relation.km")
(load-kb "cc/Meronymic-Relation.km")
(load-kb "cc/Participant-Relation.km")
(load-kb "cc/Spatial-Relation.km")
(load-kb "cc/Temporal-Relation.km")

(load-kb "sd.km")

;==> lt.cl <==
(load-kb "cc/text-active-phrase.km")
(load-kb "cc/text-active-sentence.km")
(load-kb "cc/text-active-verbseq.km")
(load-kb "cc/text-active-verbseq-pl.km")
(load-kb "cc/text-active-verbseq-sg.km")
(load-kb "cc/text-argslots.km")
(load-kb "cc/text-arguments.km")
(load-kb "cc/text-base-phrase.km")
(load-kb "cc/text-def-determiner.km")
(load-kb "cc/text-def-head.km")
(load-kb "cc/text-definition-sentence.km")
(load-kb "cc/text-description.km")
(load-kb "cc/text-dobj.km")
(load-kb "cc/text-dobj-phrase.km")
(load-kb "cc/text-existential-there.km")
(load-kb "cc/text-gen.km")
(load-kb "cc/text-gloss.km")
(load-kb "cc/text-head.km")
(load-kb "cc/text-indef-determiner.km")
(load-kb "cc/text-indef-head.km")
(load-kb "cc/text-indef-phrase.km")
(load-kb "cc/text-nominalization.km")
(load-kb "cc/text-nom-sentence.km")
(load-kb "cc/text-number.km")
(load-kb "cc/text-particle.km")
(load-kb "cc/text-passive-phrase.km")
(load-kb "cc/text-passive-sentence.km")
(load-kb "cc/text-passive-verbseq.km")
(load-kb "cc/text-passive-verbseq-pl.km")
(load-kb "cc/text-passive-verbseq-sg.km")
(load-kb "cc/text-phrase.km")
(load-kb "cc/text-postmods.km")
(load-kb "cc/text-postmodslots.km")
(load-kb "cc/text-premods.km")
(load-kb "cc/text-premodslots.km")
(load-kb "cc/text-sentence.km")
(load-kb "cc/text-slot.km")
(load-kb "cc/text-subj.km")
(load-kb "cc/text-subj-phrase.km")
