(defvar *nlp3*
'(("1A" ((NP ADULT_NN) (NP (NN ADULT))))
 ("1B" (((NP AGE_NN) (VP >_VBD) (NP =_SYM 18_CD YEARS_NNS)) ;NIL
	(FRAG
	   (S
	       (VP (VBD AGE) (-RRB- -RRB-) (NP (NP (NNP =)) (NP (CD 18))) (NP (NNS YEARS)))))
							    ))
 ("1C"
  (((NP AGE_NN) (VP <_VBP) (NP =_SYM 75_CD YEARS_NNS))
   (SQ (VP (VBP AGE) (NP (-LRB- -LRB-) (NNP =) (CD 75) (NNS YEARS))))
   (NP (NP (NN AGE)) (-LRB- -LRB-) (NP (NP (CD =)) (NP (CD 75) (NNS YEARS))))))
 ("2A"
  ((NP CORONARY_JJ HEART_NN DISEASE_NN)
   (FRAG (NP (JJ CORONARY) (NN HEART) (NN DISEASE)))
   (NP (JJ CORONARY) (NN HEART) (NN DISEASE))))
 ("2B"
  ((NP CORONARY_JJ HEART_NN DISEASE_NN RISK_NN FACTORS_NNS)
   (NP (NP (JJ CORONARY) (NN HEART) (NN DISEASE)) (NP (NN RISK) (NNS FACTORS)))
   (NP (JJ CORONARY) (NN HEART) (NN DISEASE) (NN RISK) (NNS FACTORS))))
 ("3A" ((NP DYSLIPIDEMIA_NN) (NP (NN DYSLIPIDEMIA)) (INTJ (UH DYSLIPIDEMIA))))
 ("3B"
  (((VP TREATED_VBN) (ADVP APPROPRIATELY_RB) (PP FOR_IN) (NP DYSLIPIDEMIA_NN))
   (VP (VBN TREATED) (ADVP (RB APPROPRIATELY))
    (PP (IN FOR) (NP (NN DYSLIPIDEMIA))))
   (S
    (VP (VBN TREATED) (ADVP (RB APPROPRIATELY))
     (PP (IN FOR) (NP (NN DYSLIPIDEMIA)))))))
 ("4A" ((NP STABLE_NN) (ADJP (JJ STABLE)) (FRAG (JJ STABLE))))
 ("5A"
  (((NP PREVIOUS_JJ EXPOSURE_NN) (PP TO_TO)
    (NP ANY_DT CHOLESTERYL-ESTER_NN TRANSFER_NN PROTEIN_NN INHIBITOR_NN))
   (NP (NP (JJ PREVIOUS) (NN EXPOSURE))
    (PP (TO TO)
     (NP (DT ANY) (JJ CHOLESTERYL-ESTER) (NN TRANSFER) (NN PROTEIN)
      (NN INHIBITOR))))
   (NP
    (NP (NP (JJ PREVIOUS) (NN EXPOSURE))
     (PP (TO TO)
      (NP (DT ANY) (JJ CHOLESTERYL-ESTER) (NN TRANSFER) (NN PROTEIN))))
    (NN INHIBITOR))))
 ("5B"
  (((NP PREVIOUS_JJ EXPOSURE_NN) (PP TO_TO)
    (NP ANY_DT CHOLESTERYL-ESTER_NN TRANSFER_NN PROTEIN_NN VACCINE_NN))
   (NP (NP (JJ PREVIOUS) (NN EXPOSURE))
    (PP (TO TO)
     (NP (DT ANY) (JJ CHOLESTERYL-ESTER) (NN TRANSFER) (NN PROTEIN)
      (NN VACCINE))))))
 ("6A"
  (((NP SIGNIFICANT_JJ CORONARY_JJ EVENTS_NNS) (PP WITHIN_IN)
    (NP 3_CD MONTHS_NNS))
   (NP (NP (JJ SIGNIFICANT) (JJ CORONARY) (NNS EVENTS))
    (PP (IN WITHIN) (NP (CD 3) (NNS MONTHS))))))
 ("6B"
  (((NP TRANSIENT_NN ISCHEMIC_JJ ATTACKS_NNS) (PP WITHIN_IN)
    (NP 3_CD MONTHS_NNS))
   (NP (NP (JJ TRANSIENT) (JJ ISCHEMIC) (NNS ATTACKS))
    (PP (IN WITHIN) (NP (CD 3) (NNS MONTHS))))
   (NP (NP (JJ TRANSIENT) (NN ISCHEMIC) (NNS ATTACKS))
    (PP (IN WITHIN) (NP (CD 3) (NNS MONTHS))))))
 ("6C"
  (((NP CEREBROVASCULAR_JJ ACCIDENT_NN) (PP WITHIN_IN) (NP 3_CD MONTHS_NNS))
   (NP (NP (NN CEREBROVASCULAR) (NN ACCIDENT))
    (PP (IN WITHIN) (NP (CD 3) (NNS MONTHS))))
   (S
    (VP (VB CEREBROVASCULAR) (NP (NN ACCIDENT))
     (PP (IN WITHIN) (NP (CD 3) (NNS MONTHS)))))))
 ("7A"
  ((NP SEVERE_JJ ANEMIA_NN) (NP (JJ SEVERE) (NN ANEMIA))
   (NP (JJ SEVERE) (NNP ANEMIA))))
 ("8A"
  ((NP UNCONTROLLED_JJ HYPERTENSION_NN)
   (NP (JJ UNCONTROLLED) (NN HYPERTENSION))))
 ("9A"
  ((NP POORLY_RB CONTROLLED_VBN DIABETES_NNS)
   (SINV (ADVP (RB POORLY)) (VP (VBD CONTROLLED)) (NP (NNS DIABETES)))
   (NP (ADJP (RB POORLY) (VBN CONTROLLED)) (NN DIABETES))))
 ("10A" (((NP AGE_NN) (VP >_VBD) (NP =_SYM 18_CD YEARS_NNS)) ;NIL
	(FRAG
	   (S
	       (VP (VBD AGE) (-RRB- -RRB-) (NP (NP (NNP =)) (NP (CD 18))) (NP (NNS YEARS)))))
							     ))
 ("11A" ((NP WOMEN_NNS) (NP (NNS WOMEN))))
 ("11B" ((NP POSTMENOPAUSAL_NN) (NP (NN POSTMENOPAUSAL))))
 ("11C" ((NP WOMEN_NNS) (NP (NNS WOMEN))))
 ("11D"
  (((VP USING_VBG) (NP A_DT HIGHLY_RB EFFECTIVE_JJ METHOD_NN) (PP FOR_IN)
    (NP AVOIDANCE_NN) (PP OF_IN) (NP PREGNANCY_NN))
   (S
    (VP (VBG USING)
     (NP (NP (DT A) (ADJP (RB HIGHLY) (JJ EFFECTIVE)) (NN METHOD))
      (PP (IN FOR)
       (NP (NP (NN AVOIDANCE)) (PP (IN OF) (NP (NN PREGNANCY))))))))
   (S
    (VP (VBG USING) (NP (DT A) (ADJP (RB HIGHLY) (JJ EFFECTIVE)) (NN METHOD))
     (PP (IN FOR)
      (NP (NP (NN AVOIDANCE)) (PP (IN OF) (NP (NN PREGNANCY)))))))))
 ("12A"
  ((NP CURRENT_JJ STATIN_NN THERAPY_NN)
   (FRAG (NP (JJ CURRENT) (NN STATIN) (NN THERAPY)))
   (NP (JJ CURRENT) (NN STATIN) (NN THERAPY))))
 ("13A"
  ((NP CHRONIC_NNP CORONARY_JJ HEART_NN DISEASE_NN)
   (NP (NP (JJ CHRONIC) (JJ CORONARY) (NN HEART)) (NP (NN DISEASE)))
   (NP (JJ CHRONIC) (JJ CORONARY) (NN HEART) (NN DISEASE))))
 ;("14A" ((NP AGE_NN >_NN) NIL))
 ("14A" ((NP AGE_NN >_NN)
	  (FRAG
	      (S
		   (VP (VBD AGE) (-RRB- -RRB-) (NP (NP (NNP =)) (NP (CD 60)))
		           (NP (NNS YEARS))))))
  )
 ("14B"
  (((NP DIABETES_NNP REQUIRING_VBG TREATMENT_NN) (PP WITH_IN)
    (NP MEDICATION_NN))
   (FRAG (NP (NNP DIABETES))
    (S
     (VP (VBG REQUIRING) (NP (NN TREATMENT))
      (PP (IN WITH) (NP (NN MEDICATION))))))
   (S (NP (NNP DIABETES))
    (VP (VBG REQUIRING) (NP (NN TREATMENT))
     (PP (IN WITH) (NP (NN MEDICATION)))))))
 ("14C"
  ((NP LOW_NNP HDL_NNP CHOLESTEROL_NN)
   (NP (NNP LOW) (NNP HDL) (NNP CHOLESTEROL))))
 ("14D"
  (((ADVP CURRENTLY_RB) (VP SMOKE_NN) (NP CIGARETTES_NNS))
   (S (ADVP (RB CURRENTLY)) (VP (VB SMOKE) (NP (NNS CIGARETTES))))
   (SQ (ADVP (RB CURRENTLY)) (VP (VBP SMOKE) (NP (NNS CIGARETTES))))))
 ("14E"
  (((VP STOPPED_VBN SMOKING_VBG) (PP WITHIN_IN) (NP THE_DT PAST_NN)
    (NP 3_CD MONTHS_NNS))
   (SINV (VP (VBD STOPPED))
    (NP (NP (NN SMOKING))
     (PP (IN WITHIN) (NP (DT THE) (JJ PAST) (CD 3) (NNS MONTHS)))))
   (S
    (VP (VBD STOPPED)
     (S
      (VP (VBG SMOKING)
       (PP (IN WITHIN) (NP (DT THE) (JJ PAST) (CD 3) (NNS MONTHS)))))))))
 ("14F"
  (((VP DIAGNOSED_VBN) (NP MILD_JJ REDUCTION_NN) (PP IN_IN)
    (NP KIDNEY_NN FUNCTION_NN))
   (S
    (NP (NP (VBN DIAGNOSED) (JJ MILD) (NN REDUCTION))
     (PP (IN IN) (NP (NN KIDNEY) (NN FUNCTION)))))
   (NP (NP (VBN DIAGNOSED) (JJ MILD) (NN REDUCTION))
    (PP (IN IN) (NP (NN KIDNEY) (NN FUNCTION))))))
 ("14G"
  (((VP DIAGNOSED_VBN) (NP MODERATE_JJ REDUCTION_NN) (PP IN_IN)
    (NP KIDNEY_NN FUNCTION_NN))
   (S
    (NP (NP (VBN DIAGNOSED) (JJ MODERATE) (NN REDUCTION))
     (PP (IN IN) (NP (NN KIDNEY) (NN FUNCTION)))))
   (NP (NP (JJ DIAGNOSED) (JJ MODERATE) (NN REDUCTION))
    (PP (IN IN) (NP (NN KIDNEY) (NN FUNCTION))))))
 ("14H"
  ((NP CAROTID_NN ARTERY_NN DISEASE_NN)
   (FRAG (NP (JJ CAROTID) (NN ARTERY) (NN DISEASE)))
   (NP (NN CAROTID) (NN ARTERY) (NN DISEASE))))
 ("14I"
  (((NP ISCHEMIC_JJ STROKE_NN) (NP MORE_JJR THAN_IN 3_CD MONTHS_NNS)
    (ADVP PRIOR_RB) (VP TO_TO STUDY_VB) (NP ENTRY_NN))
   (FRAG
    (NP (NP (JJ ISCHEMIC) (NN STROKE))
     (ADVP (NP (QP (JJR MORE) (IN THAN) (CD 3)) (NNS MONTHS)) (RB PRIOR)
      (PP (TO TO) (NP (NN STUDY) (NN ENTRY))))))
   (S
    (VP (VB ISCHEMIC) (NP (NN STROKE))
     (ADVP (NP (QP (JJR MORE) (IN THAN) (CD 3)) (NNS MONTHS)) (RB PRIOR)
      (S (VP (TO TO) (VP (VB STUDY) (NP (NN ENTRY))))))))))
 ("14J"
  ((NP PERIPHERAL_JJ ARTERIAL_NN DISEASE_NN)
   (FRAG (NP (JJ PERIPHERAL) (JJ ARTERIAL) (NN DISEASE)))
   (NP (JJ PERIPHERAL) (NN ARTERIAL) (NN DISEASE))))
 ("15A"
  ((NP PLANNED_NNP CORONARY_JJ REVASCULARIZATION_NN)
   (NP (NNP PLANNED) (NNP CORONARY) (NNP REVASCULARIZATION))
   (NP (ADJP (NNP PLANNED) (JJ CORONARY)) (NN REVASCULARIZATION))))
 ("15B"
  ((NP PLANNED_VBN STENT_NN PLACEMENT_NN)
   (SINV (VP (VBD PLANNED)) (NP (JJ STENT) (NN PLACEMENT)))
   (NP (JJ PLANNED) (JJ STENT) (NN PLACEMENT))))
 ("15C"
  ((NP PLANNED_VBN HEART_NN) (NP (JJ PLANNED) (NN HEART) (NNS BYPASS))
   (NP (JJ PLANNED) (NN HEART) (NN BYPASS))))
 ("15D"
  ((NP PLANNED_VBN OTHER_JJ MAJOR_JJ SURGICAL_JJ PROCEDURE_NN)
   (VP (VBN PLANNED) (NP (JJ OTHER) (JJ MAJOR) (JJ SURGICAL) (NN PROCEDURE)))
   (NP (JJ PLANNED) (JJ OTHER) (JJ MAJOR) (JJ SURGICAL) (NN PROCEDURE))))
 ("16A"
  ((NP LIVER_NN DISEASE_NN) (NP (JJ LIVER) (NN DISEASE))
   (NP (NN LIVER) (NN DISEASE))))
 ("17A"
  (((NP SEVERE_JJ REDUCTION_NN) (PP IN_IN) (NP KIDNEY_NN FUNCTION_NN))
   (NP (NP (JJ SEVERE) (NN REDUCTION))
    (PP (IN IN) (NP (NN KIDNEY) (NN FUNCTION))))
   (NP (NP (NN SEVERE) (NN REDUCTION))
    (PP (IN IN) (NP (NN KIDNEY) (NN FUNCTION))))))
 ("17B"
  (((NP REMOVAL_NN) (PP OF_IN) (NP A_DT KIDNEY_NN))
   (NP (NP (NN REMOVAL)) (PP (IN OF) (NP (DT A) (NN KIDNEY))))))
 ("17C" ((NP KIDNEY_NN TRANSPLANT_NN) (NP (NN KIDNEY) (NN TRANSPLANT))))
 ("18A"
  ((NP SEVERE_NNP HEART_NN FAILURE_NN)
   (FRAG (NP (JJ SEVERE) (NN HEART) (NN FAILURE)))
   (NP (JJ SEVERE) (NN HEART) (NN FAILURE))))
 ("19A"
  (((NP BLOOD_NN PRESSURE_NN) (ADJP HIGHER_JJR) (PP THAN_IN) (ADJP NORMAL_JJ))
   (SQ (VBP BLOOD) (VP (NN PRESSURE))
    (ADJP (ADVP (JJR HIGHER) (IN THAN)) (JJ NORMAL)))
   (FRAG (NP (JJ BLOOD) (NN PRESSURE))
    (ADJP (ADJP (JJR HIGHER)) (PP (IN THAN) (ADJP (JJ NORMAL)))))))
 ("19B"
  ((NP ANTI-HYPERTENSIVE_JJ LIFESTYLE_NN CHANGES_NNS)
   (NP (JJ ANTI-HYPERTENSIVE) (NN LIFESTYLE) (NNS CHANGES))))
 ("19C"
  (((NP TREATMENT_NN) (PP WITH_IN) (NP ANTI-HYPERTENSIVE_JJ MEDICATIONS_NNS))
   (NP (NP (NN TREATMENT))
    (PP (IN WITH) (NP (JJ ANTI-HYPERTENSIVE) (NNS MEDICATIONS))))))
 ("20A"
  (((NP LIFE-THREATENING_NN DISEASE_NN) (VP EXCLUDING_VBG)
    (NP HEART_NN DISEASE_NN))
   (SQ (VBP LIFE-THREATENING) (NP (NN DISEASE))
    (VP (VBG EXCLUDING) (NP (NN HEART) (NN DISEASE))))
   (NP (NP (JJ LIFE-THREATENING) (NN DISEASE) (NNP EXCLUDING))
    (NP (NN HEART) (NN DISEASE)))))
 ("20B"
  (((NP LIFE_NN EXPECTANCY_NN) (VP <_VBD) (NP =_SYM 2_CD YEARS_NNS))
   (S (NP (NN LIFE))
    (VP (VBZ EXPECTANCY) (NP (-LRB- -LRB-) (NNP =) (CD 2) (NNS YEARS))))
   (NP (NP (NN LIFE) (NN EXPECTANCY)) (-LRB- -LRB-)
    (NP (NP (CD =)) (NP (CD 2) (NNS YEARS))))))
 ("21A"
  ((NP SEVERE_JJ ASTHMA_NN) (NP (JJ SEVERE) (NN ASTHMA))
   (NP (NN SEVERE) (NN ASTHMA))))
 ("21B"
  ((NP POORLY_RB CONTROLLED_VBN ASTHMA_NN)
   (S (VP (ADVP (RB POORLY)) (VBN CONTROLLED) (NP (NN ASTHMA))))
   (NP (ADJP (RB POORLY) (VBN CONTROLLED)) (NN ASTHMA))))
 ("21C"
  (((VP TAKING_VBG) (NP ASTHMA_NN MEDICATION_NN))
   (S (VP (VBG TAKING) (NP (NN ASTHMA) (NN MEDICATION))))))
 ("22A" (PREGNANT_JJ (ADJP (JJ PREGNANT)) (FRAG (JJ PREGNANT))))
 ("23A"
  (((NP PREVIOUS_JJ SEVERE_JJ ALLERGIC_JJ RESPONSE_NN) (PP TO_TO) (NP FOOD_NN))
   (NP (NP (JJ PREVIOUS) (JJ SEVERE) (JJ ALLERGIC) (NN RESPONSE))
    (PP (TO TO) (NP (NN FOOD))))))
 ("23B"
  (((NP PREVIOUS_JJ SEVERE_JJ ALLERGIC_JJ RESPONSE_NN) (VP TO_TO DRINK_VB))
   (S (NP (JJ PREVIOUS) (JJ SEVERE) (JJ ALLERGIC) (NN RESPONSE))
    (VP (TO TO) (VP (VB DRINK))))
   (S (NP (JJ PREVIOUS) (ADJP (JJ SEVERE) (JJ ALLERGIC)) (NN RESPONSE))
    (VP (TO TO) (VP (VB DRINK))))))
 ("23C"
  (((NP PREVIOUS_JJ SEVERE_JJ ALLERGIC_JJ RESPONSE_NN) (PP TO_TO)
    (NP INSECT_NN STINGS_NNS))
   (NP (NP (JJ PREVIOUS) (JJ SEVERE) (JJ ALLERGIC) (NN RESPONSE))
    (PP (TO TO) (NP (JJ INSECT) (NNS STINGS))))))
 ("24A"
  (((NP DRUG_NN ABUSE_NN) (PP WITHIN_IN) (NP THE_DT PAST_NN)
    (NP 6_CD MONTHS_NNS))
   (NP (NP (NNP DRUG))
    (NP (NP (NN ABUSE))
     (PP (IN WITHIN) (NP (DT THE) (JJ PAST) (CD 6) (NNS MONTHS)))))
   (NP (NP (NN DRUG) (NN ABUSE))
    (PP (IN WITHIN) (NP (DT THE) (JJ PAST) (CD 6) (NNS MONTHS))))))
 ("24B"
  (((NP ALCOHOL_NN ABUSE_NN) (PP WITHIN_IN) (NP THE_DT PAST_NN)
    (NP 6_CD MONTHS_NNS))
   (NP (NP (NN ALCOHOL) (NN ABUSE))
    (PP (IN WITHIN) (NP (DT THE) (JJ PAST) (CD 6) (NNS MONTHS))))))
 ("24C" ((NP MENTAL_JJ IMPAIRMENT_NN) (NP (JJ MENTAL) (NN IMPAIRMENT))))
 ("24D"
  ((NP PSYCHOLOGICAL_JJ IMPAIRMENT_NN)
   (NP (JJ PSYCHOLOGICAL) (NN IMPAIRMENT))))
 ("25A"
  ((NP STABLE_JJ CORONARY_JJ HEART_NN DISEASE_NN)
   (S (VP (VB STABLE) (NP (JJ CORONARY) (NN HEART) (NN DISEASE))))
   (NP (JJ STABLE) (JJ CORONARY) (NN HEART) (NN DISEASE))))
 ("26A"
  ((NP SYMPTOMATIC_JJ ANGINA_NN PECTORIS_NN)
   (NP (JJ SYMPTOMATIC) (NN ANGINA) (NNS PECTORIS))
   (NP (NN SYMPTOMATIC) (NN ANGINA) (NN PECTORIS))))
 ("27A"
  ((NP CORONARY_JJ HEART_NN DISEASE_NN)
   (FRAG (NP (JJ CORONARY) (NN HEART) (NN DISEASE)))
   (NP (JJ CORONARY) (NN HEART) (NN DISEASE))))
 ("27B" ((NP ANGIOGRAPHY_NN) (ADVP (RB ANGIOGRAPHY)) (INTJ (UH ANGIOGRAPHY))))
 ("27C"
  ((NP CORONARY_JJ HEART_NN DISEASE_NN)
   (FRAG (NP (JJ CORONARY) (NN HEART) (NN DISEASE)))
   (NP (JJ CORONARY) (NN HEART) (NN DISEASE))))
 ("27D"
  (((VP EXERCISE_VBP) (NP STRESS_NN TESTING_VBG))
   (S (VP (VB EXERCISE) (NP (NN STRESS) (NN TESTING))))
   (S (VP (VB EXERCISE) (NP (NN STRESS)) (ADVP (NN TESTING))))))
 ("28A" ((NP CURRENT_JJ SMOKERS_NNS) (NP (JJ CURRENT) (NNS SMOKERS))))
 ("29A"
  (((NP HISTORY_NN) (PP OF_IN) (NP ARRHYTHMIA_NN))
   (NP (NP (NN HISTORY)) (PP (IN OF) (NP (NN ARRHYTHMIA))))))
 ("30A"
  ((NP SEVERE_JJ 3_CD VESSEL_NN CORONARY_JJ HEART_NN DISEASE_NN)
   (SINV (VP (VBZ SEVERE))
    (NP (CD 3) (JJ VESSEL) (JJ CORONARY) (NN HEART) (NN DISEASE)))
   (NP (NNP SEVERE) (ADJP (CD 3) (NN VESSEL)) (JJ CORONARY) (NN HEART)
    (NN DISEASE))))
 ("30B"
  (((NP LEFT_VBN MAIN_JJ STEM_NN STENOSIS_NN) (NP THAT_WDT)
    (VP HAS_VBZ NOT_RB BEEN_VBN REVASCULARISED_VBN))
   (SINV (VP (VBD LEFT))
    (NP (NP (JJ MAIN) (NN STEM) (NNS STENOSIS))
     (SBAR (WHNP (WDT THAT))
      (S (VP (VBZ HAS) (RB NOT) (VP (VBN BEEN) (VP (VBN REVASCULARISED))))))))
   (S
    (VP (VBD LEFT)
     (NP (NP (JJ MAIN) (NN STEM) (NN STENOSIS))
      (SBAR (WHNP (WDT THAT))
       (S
        (VP (VBZ HAS) (RB NOT)
         (VP (VBN BEEN) (VP (VBN REVASCULARISED)))))))))))
 ("31A"
  (((VP RESTING_VBG) (NP CONDUCTION_NN ABNORMALITY_NN))
   (S (VP (VBG RESTING) (NP (NN CONDUCTION) (NN ABNORMALITY))))
   (NP (NN RESTING) (NN CONDUCTION) (NN ABNORMALITY))))
 ("32A"
  ((NP DIGOXIN_NNP THERAPY_NN) (NP (NN DIGOXIN) (NN THERAPY))
   (NP (NNP DIGOXIN) (NNP THERAPY))))
 ("33A"
  ((NP UNCONTROLLED_JJ HYPERTENSION_NN)
   (NP (JJ UNCONTROLLED) (NN HYPERTENSION))))
 ("34A" ((NP RENAL_NNP FAILURE_NN) (NP (JJ RENAL) (NN FAILURE))))
 ("35A"
  ((NP HEPATIC_JJ FAILURE_NN) (NP (JJ HEPATIC) (NN FAILURE))
   (NP (NNP HEPATIC) (NNP FAILURE))))
 ("36A"
  ((NP ACUTE_JJ CORONARY_JJ SYNDROME_NN)
   (S (VP (VB ACUTE) (NP (JJ CORONARY) (NN SYNDROME))))
   (NP (NN ACUTE) (JJ CORONARY) (NN SYNDROME))))
 ("36B"
  (((NP UNSTABLE_JJ ANGINAL_JJ SYMPTOMS_NNS) (PP WITHIN_IN)
    (NP 3_CD MONTHS_NNS))
   (NP (NP (JJ UNSTABLE) (JJ ANGINAL) (NNS SYMPTOMS))
    (PP (IN WITHIN) (NP (CD 3) (NNS MONTHS))))))
 ("37A"
  (((NP SIGNIFICANT_JJ OCCUPATION_NN EXPOSURE_NN) (PP TO_TO)
    (NP AIR_NN POLLUTION_NN))
   (FRAG (NP (JJ SIGNIFICANT) (NN OCCUPATION) (NN EXPOSURE))
    (S (VP (TO TO) (VP (VB AIR) (NP (NN POLLUTION))))))
   (SQ (NP (NN SIGNIFICANT) (NN OCCUPATION) (NN EXPOSURE))
    (PP (TO TO) (NP (NN AIR) (NN POLLUTION))))))
 ("38A"
  ((NP STABLE_JJ CORONARY_JJ ARTERY_NN DISEASE_NN)
   (S (VP (VB STABLE) (NP (JJ CORONARY) (NN ARTERY) (NN DISEASE))))
   (NP (JJ STABLE) (JJ CORONARY) (NN ARTERY) (NN DISEASE))))
 ("39A" ((NP MEN_NNS) (NP (NNS MEN))))
 ("39B" ((NP WOMEN_NNS) (NP (NNS WOMEN))))
 ("39C" ((NP POSTMENOPAUSAL_NN) (NP (NN POSTMENOPAUSAL))))
 ;("40A" ((NP AGE_NN >_NN) NIL))
 ("40A" ((NP AGE_NN >_NN)
	  (FRAG
	      (S
		   (VP (VBD AGE) (-RRB- -RRB-) (NP (NP (NNP =)) (ADJP (CD 20)))
		           (NP (NNS YEARS))))))
  )
 ("40B"
  (((NP AGE_NN) (VP <_VBD) (NP =_SYM 80_CD YEARS_NNS))
   (SQ (VP (VBP AGE) (NP (-LRB- -LRB-) (NNP =) (CD 80) (NNS YEARS))))
   (NP (NP (NN AGE)) (-LRB- -LRB-) (NP (NP (CD =)) (NP (CD 80) (NNS YEARS))))))
 ("41A"
  (((NP WEIGHT_NN) (PP <_IN) (NP 115_CD) KG_.)
   (S (VP (VB WEIGHT) (-LRB- -LRB-) (NP (CD 115)) (S (VP (VB KG)))))
   (NP (NP (NN WEIGHT)) (-LRB- -LRB-) (NP (CD 115) (NNP KG)))))
 ("41B"
  (((NP BODY_NN MASS_NN INDEX_NN) (PP >_IN) (NP =_SYM 18.5_CD) KG_M2_CD)
   (NP (NP (NN BODY) (NN MASS) (NN INDEX) (-RRB- -RRB-) (NN =))
    (NP (CD 18.5) (NNS KG/M2)))
   (NP (NP (NN BODY) (NN MASS) (NN INDEX) (-RRB- -RRB-))
    (NP (QP (SYM =) (CD 18.5) (CD KG/M2))))))
 ("41C"
  ((NP BODY_NN MASS_NN INDEX_NN <_NN)
   (NP (NP (NN BODY) (NN MASS) (NN INDEX))
    (NP (-LRB- -LRB-) (JJ =) (CD 35) (NN KG/M2)))
   (NP (NP (NN BODY) (NN MASS) (NN INDEX)) (-LRB- -LRB-)
    (NP (QP (SYM =) (CD 35) (CD KG/M2))))))
 ("42A"
  ((NP CORONARY_JJ ARTERY_NN DISEASE_NN)
   (FRAG (NP (JJ CORONARY) (NN ARTERY) (NN DISEASE)))
   (NP (JJ CORONARY) (NN ARTERY) (NN DISEASE))))
 ("42B"
  (((NP THE_DT PRESENCE_NN) (PP OF_IN) (NP LESIONS_NNS) (PP ON_IN)
    (NP CORONARY_JJ ANGIOGRAPHY_NN))
   (NP (NP (DT THE) (NN PRESENCE))
    (PP (IN OF)
     (NP (NP (NNS LESIONS))
      (PP (IN ON) (NP (JJ CORONARY) (NN ANGIOGRAPHY))))))))
 ("42C"
  ((NP CORONARY_JJ ARTERY_NN DISEASE_NN)
   (FRAG (NP (JJ CORONARY) (NN ARTERY) (NN DISEASE)))
   (NP (JJ CORONARY) (NN ARTERY) (NN DISEASE))))
 ("42D"
  (((NP HISTORY_NN) (PP OF_IN) (NP MYOCARDIAL_JJ INFARCTION_NN))
   (NP (NP (NN HISTORY)) (PP (IN OF) (NP (JJ MYOCARDIAL) (NN INFARCTION))))))
 ("42E"
  ((NP CORONARY_JJ ARTERY_NN DISEASE_NN)
   (FRAG (NP (JJ CORONARY) (NN ARTERY) (NN DISEASE)))
   (NP (JJ CORONARY) (NN ARTERY) (NN DISEASE))))
 ("42F"
  ((NP POSITIVE_JJ STRESS_NN TEST_NN)
   (FRAG (NP (JJ POSITIVE) (NN STRESS) (NN TEST)))
   (NP (JJ POSITIVE) (NN STRESS) (NN TEST))))
 ("43A"
  ((NP A_DT STENT_NN PROCEDURE_NN) (NP (DT A) (NN STENT) (NN PROCEDURE))))
 ("43B"
  (((ADJP STABLE_JJ) (PP FOR_IN) (NP ONE_CD MONTH_NN) (PP AFTER_IN)
    (NP THE_DT STENT_NN PROCEDURE_NN))
   (ADJP (JJ STABLE)
    (PP (IN FOR)
     (NP (NP (CD ONE) (NN MONTH))
      (PP (IN AFTER) (NP (DT THE) (JJ STENT) (NN PROCEDURE))))))
   (ADJP (JJ STABLE)
    (PP (IN FOR)
     (NP (NP (CD ONE) (NN MONTH))
      (PP (IN AFTER) (NP (DT THE) (NN STENT) (NN PROCEDURE))))))))
 ("44A" ((NP ENGLISH_NNP LANGUAGE_NN) (NP (JJ ENGLISH) (NN LANGUAGE))))
 ("45A" ((NP HEART_NN FAILURE_NN) (NP (NN HEART) (NN FAILURE))))
 ("46A"
  (((NP HISTORY_NN) (PP OF_IN) (NP ALLERGY_NN) (PP TO_TO) (NP NUTS_NNS)
    (PP OF_IN) (NP ANY_DT KIND_NN))
   (NP (NP (NN HISTORY)) (PP (IN OF) (NP (NN ALLERGY)))
    (PP (TO TO) (NP (NP (NNS NUTS)) (PP (IN OF) (NP (DT ANY) (NN KIND))))))
   (NP (NP (NN HISTORY)) (PP (IN OF) (NP (NN ALLERGY)))
    (PP (TO TO) (NP (NNS NUTS))) (PP (IN OF) (NP (DT ANY) (NN KIND))))))
 ("46B"
  (((NP KNOWN_VBN ALLERGY_NN) (PP TO_TO) (NP NUTS_NNS) (PP OF_IN)
    (NP ANY_DT KIND_NN))
   (VP (VBN KNOWN) (NP (NN ALLERGY))
    (PP (TO TO) (NP (NP (NNS NUTS)) (PP (IN OF) (NP (DT ANY) (NN KIND))))))
   (NP (NP (VBN KNOWN) (NN ALLERGY)) (PP (TO TO) (NP (NNS NUTS)))
    (PP (IN OF) (NP (DT ANY) (NN KIND))))))
 ("47A"
  (((NP WOMEN_NNS) (PP WITH_IN)
    (NP A_DT POSITIVE_JJ URINE_NN BETA_NN HCG_NNP PREGNANCY_NN TEST_NN))
   (NP (NP (NNP WOMEN))
    (PP (IN WITH)
     (NP (DT A) (JJ POSITIVE) (NN URINE) (NN BETA) (NN HCG) (NN PREGNANCY)
      (NN TEST))))
   (NP (NP (NNS WOMEN))
    (PP (IN WITH)
     (NP (DT A) (JJ POSITIVE) (NN URINE) (JJ BETA) (NNP HCG) (NN PREGNANCY)
      (NN TEST))))))
 ("47B"
  ((NP LACTATING_VBG WOMEN_NNS) (NP (JJ LACTATING) (NNS WOMEN))
   (NP (NN LACTATING) (NNS WOMEN))))
 ("47C"
  (((NP WOMEN_NNS) (NP WHO_WP) (VP ARE_VBP PLANNING_VBG TO_TO BECOME_VB)
    PREGNANT_JJ)
   (S
    (NP (NP (NNS WOMEN))
     (SBAR (WHNP (WP WHO))
      (S
       (VP (VBP ARE)
        (VP (VBG PLANNING)
         (S (VP (TO TO) (VP (VB BECOME) (ADJP (JJ PREGNANT)))))))))))
   (S (NP (NP (NNS WOMEN)) (SBAR (WHNP (WP WHO))))
    (VP (VBP ARE)
     (VP (VBG PLANNING)
      (S (VP (TO TO) (VP (VB BECOME) (ADJP (JJ PREGNANT))))))))))
 ("48A"
  (((NP REGULAR_JJ CONSUMPTION_NN) (PP OF_IN) (NP NUTS_NNS) (PP FOR_IN)
    (NP 6_CD WEEKS_NNS) (ADVP PRIOR_RB) (VP TO_TO STUDY_VB) (NP ADMISSION_NN)
    (PP >_IN) (NP =_SYM) (NP 5_CD OZ_WEEK_NN))
   (NP
    (NP (NP (JJ REGULAR) (NN CONSUMPTION)) (PP (IN OF) (NP (NNS NUTS)))
     (PP (IN FOR)
      (NP (NP (CD 6) (NNS WEEKS))
       (ADVP (RB PRIOR) (PP (TO TO) (NP (NN STUDY) (NN ADMISSION))))))
     (-RRB- -RRB-))
    (NP (QP (CD =) (CD 5)) (NN OZ/WEEK)))
   (NP
    (NP (NP (JJ REGULAR) (NN CONSUMPTION)) (PP (IN OF) (NP (NNS NUTS)))
     (PP (IN FOR) (NP (CD 6) (NNS WEEKS)))
     (ADJP (JJ PRIOR) (S (VP (TO TO) (VP (VB STUDY) (NP (NN ADMISSION)))))
      (-RRB- -RRB-))
     (X (SYM =)))
    (NP (CD 5) (NN OZ/WEEK)))))
 ("49A"
  (((NP CLINICAL_JJ HISTORY_NN) (PP OF_IN) (NP MAJOR_JJ ILLNESS_NN))
   (NP (NP (JJ CLINICAL) (NN HISTORY))
    (PP (IN OF) (NP (JJ MAJOR) (NN ILLNESS))))))
 ("49B"
  (((NP CLINICAL_JJ HISTORY_NN) (PP OF_IN) (NP END-STAGE_NN CANCER_NN))
   (NP (NP (JJ CLINICAL) (NN HISTORY))
    (PP (IN OF) (NP (JJ END-STAGE) (NN CANCER))))
   (NP (NP (JJ CLINICAL) (NN HISTORY))
    (PP (IN OF) (NP (NN END-STAGE) (NN CANCER))))))
 ("49C"
  (((NP CLINICAL_JJ HISTORY_NN) (PP OF_IN) (NP RENAL_JJ FAILURE_NN))
   (NP (NP (JJ CLINICAL) (NN HISTORY))
    (PP (IN OF) (NP (JJ RENAL) (NN FAILURE))))))
 ("49D"
  (((NP CLINICAL_JJ HISTORY_NN) (PP OF_IN) (NP HEPATIC_JJ FAILURE_NN))
   (NP (NP (JJ CLINICAL) (NN HISTORY))
    (PP (IN OF) (NP (JJ HEPATIC) (NN FAILURE))))))
 ("49E"
  (((NP CLINICAL_JJ HISTORY_NN) (PP OF_IN)
    (NP GASTROINTESTINAL_JJ DISORDERS_NNS) (NP THAT_WDT) (VP MAY_MD IMPAIR_VB)
    (NP ABSORPTION_NN))
   (NP (NP (JJ CLINICAL) (NN HISTORY))
    (PP (IN OF)
     (NP (NP (JJ GASTROINTESTINAL) (NNS DISORDERS))
      (SBAR (WHNP (WDT THAT))
       (S (VP (MD MAY) (VP (VB IMPAIR) (NP (NN ABSORPTION)))))))))
   (NP (NP (JJ CLINICAL) (NN HISTORY))
    (PP (IN OF)
     (NP (NP (JJ GASTROINTESTINAL) (NNS DISORDERS))
      (SBAR (WHNP (WDT THAT))
       (S (VP (MD MAY) (VP (VB IMPAIR) (NP (NNP ABSORPTION)))))))))))
 ("50A"
  (((NP REGULAR_JJ USE_NN) (PP OF_IN) (NP ORAL_JJ STEROIDS_NNS))
   (NP (NP (JJ REGULAR) (NN USE)) (PP (IN OF) (NP (JJ ORAL) (NNS STEROIDS))))))
 ("51A"
  ((NP CIGARETTE_NN SMOKING_NN) (NP (JJ CIGARETTE) (NN SMOKING))
   (NP (NN CIGARETTE) (NN SMOKING))))
 ("51B"
  ((NP NICOTINE_JJ REPLACEMENT_NN USE_NN)
   (S (VP (VB NICOTINE) (NP (NN REPLACEMENT) (NN USE))))))
 ("52A"
  (((NP REGULAR_JJ INTAKE_NN) (PP OF_IN) (NP ALCOHOLIC_JJ DRINKS_NNS >_NN)
    =_SYM 2_DAY_)
   (NP (NP (JJ REGULAR) (NN INTAKE))
    (PP (IN OF)
     (NP (JJ ALCOHOLIC) (NN DRINKS) (-RRB- -RRB-) (NN =) (NNS 2/DAY))))
   (NP
    (NP (NP (JJ REGULAR) (NN INTAKE))
     (PP (IN OF) (NP (JJ ALCOHOLIC) (NNS DRINKS))) (-RRB- -RRB-))
    (NP (NNP =) (NNP 2/DAY)))))
 ("53A"
  ((NP ILLICIT_NNP DRUG_NN USE_NN)
   (S (NP (JJ ILLICIT) (NN DRUG)) (VP (VBP USE)))
   (NP (NN ILLICIT) (NN DRUG) (NN USE))))
 ("54A"
  (((NP HISTORY_NN) (PP OF_IN) (NP A_DT PSYCHOLOGICAL_JJ ILLNESS_NN))
   (NP (NP (NN HISTORY))
    (PP (IN OF) (NP (DT A) (JJ PSYCHOLOGICAL) (NN ILLNESS))))))
 ("55A"
  (((NP DIETARY_NNP SUPPLEMENTS_NNS) (VP CONTAINING_VBG)
    (NP PHENOLIC_JJ COMPOUNDS_NNS) (NP ONE_CD MONTH_NN) (ADVP PRIOR_RB)
    (VP TO_TO STUDY_VB) (NP ADMISSION_NN))
   (FRAG (ADJP (RB DIETARY) (JJ SUPPLEMENTS))
    (S
     (VP (VBG CONTAINING) (NP (JJ PHENOLIC) (NNS COMPOUNDS))
      (PP (ADVP (NP (CD ONE) (NN MONTH)) (RB PRIOR)) (TO TO)
       (NP (NN STUDY) (NN ADMISSION))))))
   (S
    (NP (NP (JJ DIETARY) (NNS SUPPLEMENTS))
     (VP (VBG CONTAINING) (NP (NN PHENOLIC))))
    (VP (VBZ COMPOUNDS) (NP (CD ONE) (NN MONTH)) (ADVP (RB PRIOR))
     (S (VP (TO TO) (VP (VB STUDY) (NP (NN ADMISSION)))))))))
 ("55B"
  (((NP HERBAL_JJ PREPARATIONS_NNS) (VP CONTAINING_VBG)
    (NP PHENOLIC_JJ COMPOUNDS_NNS) (NP ONE_CD MONTH_NN) (ADVP PRIOR_RB)
    (VP TO_TO STUDY_VB) (NP ADMISSION_NN))
   (NP
    (NP (NP (JJ HERBAL) (NNS PREPARATIONS))
     (VP (VBG CONTAINING) (NP (JJ PHENOLIC) (NNS COMPOUNDS))))
    (S (ADVP (NP (CD ONE) (NN MONTH)) (RB PRIOR))
     (VP (TO TO) (VP (VB STUDY) (NP (NN ADMISSION))))))
   (S
    (NP (NP (JJ HERBAL) (NNS PREPARATIONS))
     (VP (VBG CONTAINING) (NP (NN PHENOLIC))))
    (VP (VBZ COMPOUNDS) (NP (CD ONE) (NN MONTH)) (ADVP (RB PRIOR))
     (S (VP (TO TO) (VP (VB STUDY) (NP (NN ADMISSION)))))))))
 ("55C"
  (((NP BERRY_NN) (VP CONTAINING_VBG) (NP PREPARATIONS_NNS)
    (NP ONE_CD MONTH_NN) (ADVP PRIOR_RB) (VP TO_TO STUDY_VB) (NP ADMISSION_NN))
   (FRAG
    (S (ADVP (RB BERRY))
     (VP (VBG CONTAINING) (NP (NNS PREPARATIONS))
      (PP (ADVP (NP (CD ONE) (NN MONTH)) (RB PRIOR)) (TO TO)
       (NP (NN STUDY) (NN ADMISSION))))))
   (S (NP (NN BERRY))
    (VP (VBG CONTAINING)
     (NP (NP (NNS PREPARATIONS)) (ADVP (NP (CD ONE) (NN MONTH)) (RB PRIOR))
      (S (VP (TO TO) (VP (VB STUDY) (NP (NN ADMISSION))))))))))
 ("55D"
  (((NP CRANBERRY_NN CAPSULES_NNS) (NP ONE_CD MONTH_NN) (ADVP PRIOR_RB)
    (VP TO_TO STUDY_VB) (NP ADMISSION_NN))
   (NP (NP (JJ CRANBERRY) (NNS CAPSULES))
    (NP (NP (CD ONE) (NN MONTH))
     (PP (RB PRIOR) (TO TO) (NP (NN STUDY) (NN ADMISSION)))))
   (S
    (NP (NP (JJ CRANBERRY) (NNS CAPSULES))
     (ADVP (NP (CD ONE) (NN MONTH)) (RB PRIOR)))
    (VP (TO TO) (VP (VB STUDY) (NP (NN ADMISSION)))))))
 ("56A"
  (((NP TREATMENT_NNP) (PP WITH_IN) (NP VITAMIN_NNP E_NNP) (PP WITHIN_IN)
    (NP 1_CD MONTH_NN) (PP OF_IN)
    (NP ENROLLMENT_NN EXCLUDING_NN VITAMIN_NN E_NNP DOSE_NN) (VP <_VBZ)
    (NP =_SYM 2_CD) RDA_.)
   (FRAG (NP (NNP TREATMENT))
    (PP (IN WITH)
     (S
      (NP (NP (NN VITAMIN) (NN E))
       (PP (IN WITHIN)
        (NP (NP (CD 1) (NN MONTH)) (PP (IN OF) (NP (NN ENROLLMENT))))))
      (VP (VBG EXCLUDING)
       (NP (NN VITAMIN) (NN E) (NN DOSE) (-LRB- -LRB-) (NN =) (CD 2)
        (NN RDA))))))
   (NP
    (NP (NP (NNP TREATMENT))
     (PP (IN WITH)
      (NP (NP (NNP VITAMIN) (NNP E))
       (PP (IN WITHIN)
        (NP (NP (CD 1) (NN MONTH))
         (PP (IN OF)
          (NP (NN ENROLLMENT) (NN EXCLUDING) (NN VITAMIN) (NN E)
           (NN DOSE))))))))
    (PRN (-LRB- -LRB-) (X (SYM =)) (2) (NP (NNP RDA))))))
 ("56B"
  (((NP TREATMENT_NNP) (PP WITH_IN) (NP VITAMIN_NNP C_NNP) (PP WITHIN_IN)
    (NP 1_CD MONTH_NN) (PP OF_IN)
    (NP ENROLLMENT_NN EXCLUDING_NN VITAMIN_NN C_NNP DOSE_NN) (PP <_IN)
    (NP =_SYM 2_CD) RDA_.)
   (FRAG (NP (NNP TREATMENT))
    (PP (IN WITH)
     (S
      (NP (NP (NN VITAMIN) (NN C))
       (PP (IN WITHIN)
        (NP (NP (CD 1) (NN MONTH)) (PP (IN OF) (NP (NN ENROLLMENT))))))
      (VP (VBG EXCLUDING)
       (NP (NN VITAMIN) (NN C) (NN DOSE) (-LRB- -LRB-) (NN =) (CD 2)
        (NN RDA))))))
   (NP
    (NP (NP (NNP TREATMENT))
     (PP (IN WITH)
      (NP (NP (NNP VITAMIN) (NNP C))
       (PP (IN WITHIN)
        (NP (NP (CD 1) (NN MONTH))
         (PP (IN OF) (NP (NN ENROLLMENT) (NN EXCLUDING) (NN VITAMIN))) (NNP C)
         (NN DOSE))))))
    (PRN (-LRB- -LRB-) (X (SYM =)) (2) (NP (NNP RDA))))))
 ("56C"
  (((NP TREATMENT_NNP) (PP WITH_IN) (NP BETA_JJ CAROTENE_NN) (PP WITHIN_IN)
    (NP 1_CD MONTH_NN) (PP OF_IN) (NP ENROLLMENT_NN))
   (S (NP (NP (NNP TREATMENT)) (PP (IN WITH) (NP (NN BETA))))
    (ADJP (JJ CAROTENE))
    (PP (IN WITHIN)
     (NP (NP (CD 1) (NN MONTH)) (PP (IN OF) (NP (NN ENROLLMENT))))))
   (S
    (VP (VBN TREATMENT)
     (PP (IN WITH)
      (NP (NP (JJ BETA) (NN CAROTENE))
       (PP (IN WITHIN)
        (NP (NP (CD 1) (NN MONTH)) (PP (IN OF) (NP (NN ENROLLMENT)))))))))))
 ("56D"
  (((NP TREATMENT_NNP) (PP WITH_IN) (NP LIPOIC_JJ ACID_NN) (PP WITHIN_IN)
    (NP 1_CD MONTH_NN) (PP OF_IN) (NP ENROLLMENT_NN))
   (FRAG (NP (NNP TREATMENT)) (PP (IN WITH) (NP (JJ LIPOIC) (NN ACID)))
    (PP (IN WITHIN)
     (NP (NP (CD 1) (NN MONTH)) (PP (IN OF) (NP (NN ENROLLMENT))))))
   (S
    (VP (VBN TREATMENT) (PP (IN WITH) (NP (JJ LIPOIC) (NN ACID)))
     (PP (IN WITHIN)
      (NP (NP (CD 1) (NN MONTH)) (PP (IN OF) (NP (NN ENROLLMENT)))))))))
 ("56E"
  (((NP TREATMENT_NNP) (PP WITH_IN) (NP OTHER_JJ FOOD_NN SUPPLEMENTS_NNS)
    (PP WITHIN_IN) (NP 1_CD MONTH_NN) (PP OF_IN) (NP ENROLLMENT_NN))
   (FRAG (NP (NNP TREATMENT))
    (PP (IN WITH) (NP (JJ OTHER) (NN FOOD) (NNS SUPPLEMENTS)))
    (PP (IN WITHIN)
     (NP (NP (CD 1) (NN MONTH)) (PP (IN OF) (NP (NN ENROLLMENT))))))
   (S
    (VP (VBN TREATMENT)
     (PP (IN WITH)
      (NP (NP (JJ OTHER) (NN FOOD) (NNS SUPPLEMENTS))
       (PP (IN WITHIN)
        (NP (NP (CD 1) (NN MONTH)) (PP (IN OF) (NP (NN ENROLLMENT)))))))))))
 ("56F"
  (((NP TREATMENT_NNP) (PP WITH_IN) (NP HERBAL_JJ SUPPLEMENTS_NNS)
    (PP WITHIN_IN) (NP 1_CD MONTH_NN) (PP OF_IN) (NP ENROLLMENT_NN))
   (FRAG (NP (NNP TREATMENT)) (PP (IN WITH) (NP (JJ HERBAL) (NNS SUPPLEMENTS)))
    (PP (IN WITHIN)
     (NP (NP (CD 1) (NN MONTH)) (PP (IN OF) (NP (NN ENROLLMENT))))))
   (S
    (VP (VBN TREATMENT)
     (PP (IN WITH)
      (NP (NP (JJ HERBAL) (NNS SUPPLEMENTS))
       (PP (IN WITHIN)
        (NP (NP (CD 1) (NN MONTH)) (PP (IN OF) (NP (NN ENROLLMENT))))))))))))
)
(defun id2prs (id) (cdr (assoc (string-upcase id) *nlp3* :test #'equal)))
;since this replaces n2.cl &co
(defun get-rec2 (id) (id2prs id))
(defun id2prsa (id) (cons id (id2prs id)))
;(defun rest-lv (lv) ;in utils now
;    (if (fulll lv) (rest lv) lv)) 
(defun id2nlp4 (id)
 (let ((prs (first-lv (id2prs id))))
  (list :nyu (rest-lv (id2nyu id)) :op (first-lv prs) :sb (second-lv prs))))
(defun id2nlp4a (id)
  (cons id (id2nlp4 id)))
;-eof
