(defvar *nyu* '(
("1A" .(S (NPL adult)))
("1B" . (S (VP age (NPL (CD >= 18) years))))
("1C" . (S (VP age (NPL (CD <= 75) years))))
("2A" . (S (NPL coronary heart disease)))
("2B" . (S (NPL coronary heart disease) (VP risk (VP factors))))
("3A" . (S (ADJP dyslipidemia)))
("3B" . (S (VP treated (NPL appropriately) (PP for (NPL dyslipidemia)))))
("4A" . (S (ADJP stable)))
("5A" .(S (ADJP previous) (NP (NPL exposure) (PP to (NPL any cholesteryl-ester transfer protein inhibitor)))))
("5B" .(S (ADJP previous) (NP (NPL exposure) (PP to (NPL any cholesteryl-ester transfer protein vaccine)))))
("6A" . (S (ADJP significant) (NP (NPL coronary events) (PP within (NPL 3 months)))))
("6B" . (S (VP transient (NPL ischemic attacks) (PP within (NPL 3 months)))))
("6C" . (S (NPL cerebrovascular accident) (VP within (NPL 3 months))))
("7A" . (S (NPL severe anemia)))
("8A" . (S (NPL uncontrolled hypertension)))
("9A" . (S (ADVP poorly) (VP controlled (NPL diabetes))))
("10A" . (S (VP age (NPL (CD >= 18) years))))
("11A" . (S (NPL women)))
("11B" . (S (ADJP postmenopausal)))
("11C" . (S (NPL women)))
("11D" . (S (VP using (NPL a (ADJP highly effective) method) (PP for (NP (NPL avoidance) (PP of (NPL pregnancy)))))))
("12A" . (S (NPL Current statin therapy)))
("13A" . (S (NPL Chronic coronary) (VP heart (VP disease))))
("14A" . (S (VP age (NPL (CD >= 60) years))))
("14B" . (S (VP Diabetes (NPL requiring treatment) (PP with (NPL medication)))))
("14C" . (S (NPL Low HDL cholesterol)))
("14D" . (S (ADVP Currently) (VP smoke (NPL cigarettes))))
("14E" . (S (VP stopped (NPL smoking) (PP within (NPL the past 3 months)))))
("14F" . (S (VP Diagnosed (NPL mild reduction) (PP in (NPL kidney function)))))
("14G" . (S (VP Diagnosed (NPL moderate reduction) (PP in (NPL kidney function)))))
("14H" . (S (NPL carotid) (VP artery (VP disease))))
("14I" . (S (NPL ischemic) (VP stroke (NPL (QP more than 3) months) (ADVP prior (PP to (NPL study entry))))))
("14J" . (S (NPL peripheral arterial disease)))
("15A" . (S (VP Planned (NPL coronary revascularization))))
("15B" . (S (VP planned (NPL stent placement))))
("15C" . (S (NPL planned heart) (VP bypass)))
("15D" . (S (VP planned (NPL other major surgical procedure))))
("16A" . (S (NPL Liver disease)))
("17A" . (S (NP (NPL Severe reduction) (PP in (NPL kidney))) (VP function)))
("17B" . (S (SS (NP (NPL removal) (PP of (NPL a kidney))))))
("17C" . (S (NPL kidney) (VP transplant)))
("18A" . (S (NPL Severe heart failure)))
("19A" . (S (NPL Blood) (VP pressure (ADJP higher) (SBAR than (SS (ADJP normal))))))
("19B" . (S (NPL anti-hypertensive lifestyle changes)))
("19C" . (S (NPL treatment) (VP with (NPL anti-hypertensive medications))))
("20A" . (S (NPL life-threatening disease EXCLUDING) (VP heart (VP disease))))
("20B" . (S (NPL life) (VP expectancy (NPL (CD <= 2) years))))
("21A" . (S (NPL Severe asthma)))
("21B" . (S (ADVP poorly) (VP controlled (NPL asthma))))
("21C" . (S (VP taking (NPL asthma medication))))
("22A" . (S (ADJP pregnant)))
("23A" . (S (ADJP Previous) (NP (NPL severe allergic response) (PP to (NPL food)))))
("23B" . (S (ADJP previous) (NP (NPL severe allergic response) (PP to (NPL drink)))))
("23C" . (S (NP (NPL previous severe allergic response) (PP to (NPL insect))) (VP stings)))
("24A" . (S (VP Drug (NPL abuse) (PP within (NPL the past 6 months)))))
("24B" . (S (VP alcohol (NPL abuse) (PP within (NPL the past 6 months)))))
("24C" . (S (NPL mental impairment)))
("24D" . (S (NPL psychological impairment)))
("25A" . (S (NPL Stable coronary) (VP heart (VP disease))))
("26A" . (S (NPL symptomatic angina pectoris)))
("27A" . (S (NPL coronary heart disease)))
("27B" . (S (ADJP angiography)))
("27C" . (S (NPL coronary heart disease)))
("27D" . (S (NPL exercise) (VP stress (NPL testing))))
("28A" . (S (NPL Current smokers)))
("29A" . (S (NP (NPL History) (PP of)) (ADJP arrhythmia)))
("30A" . (S (ADJP Severe) (NP (NPL 3 vessel) coronary heart disease)))
("30B" . (S (VP left (NP (NPL main stem stenosis) (SBAR (SS (NPL that) (VP has not (VP been (ADJP revascularised)))))))))
("31A" . (S (VP Resting (NPL conduction abnormality))))
("32A" . (S (NPL Digoxin therapy)))
("33A" . (S (NPL uncontrolled hypertension)))
("34A" . (S (NPL Renal failure)))
("35A" . (S (NPL Hepatic failure)))
("36A" . (S (NPL Acute coronary syndrome)))
("36B" . (S (ADJP unstable) (NP (NPL anginal symptoms) (PP within (NPL 3 months)))))
("37A" . (S (NPL Significant occupation) (VP exposure (TOINF (VP to (VP air (NPL pollution)))))))
("38A" . (S (NPL Stable coronary) (VP artery (VP disease))))
("39A" . (S (NPL men)))
("39B" . (S (NPL women)))
("39C" . (S (ADJP postmenopausal)))
("40A" . (S (VP age (NPL (CD >= 20) years))))
("40B" . (S (VP age (NPL (CD <= 80) years))))
("41A" . (S (VP weight (NPL (CD < 115) Kg))))
("41B" . (S (NPL body) (VP mass (NPL index (CD >= 18.5 kg/m2)))))
("41C" . (S (NPL body) (VP mass (NPL index (CD <= 35 kg/m2)))))
("42A" . (S (NPL coronary artery disease)))
("42B" . (S (NP (NPL the presence) (PP of (NP (NPL lesions) (PP on (NPL coronary))))) (ADJP angiography)))
("42C" . (S (NPL coronary artery disease)))
("42D" . (S (NP (NPL history) (PP of (NPL myocardial))) (ADJP infarction)))
("42E" . (S (NPL coronary artery disease)))
("42F" . (S (NPL positive stress test)))
("43A" . (S (NPL a stent procedure)))
("43B" . (S (NPL stable) (PP for (NP (NPL one month) (PP after (NPL the stent procedure))))))
("44A" . (S (NPL English language)))
("45A" . (S (NPL heart failure)))
("46A" . (S (SS (NP (NPL History) (PP of (NPL allergy))) (PP to (NP (NPL nuts) (PP of (NPL any kind)))))))
("46B" . (S (SS (VP known (NP (NPL allergy) (PP to (NP (NPL nuts) (PP of (NPL any kind)))))))))
("47A" . (S (NPL Women) (PP with (NP (NPL a positive urine beta) HCG pregnancy test))))
("47B" . (S (VP lactating (NPL women))))
("47C" . (S (NP (NPL women) (SBAR (WHNP who) (SS (VP are (VP planning (TOINF (VP to (VP become)))))))) (ADJP pregnant)))
("48A" . (S (ADJP Regular) (NP (NPL consumption) (PP of (NPL nuts)) (PP for (NPL 6 weeks)) (PP prior (PP to (NP (NPL study admission) (NPL (CD >= 5 oz/week))))))))
("49A" . (S (ADJP Clinical) (NP (NPL history) (PP of (NPL major illness)))))
("49B" . (S (ADJP Clinical) (NP (NPL history) (PP of (NPL end-stage cancer)))))
("49C" . (S (ADJP Clinical) (NP (NPL history) (PP of (NPL renal failure)))))
("49D" . (S (ADJP Clinical) (NP (NPL history) (PP of (NPL hepatic failure)))))
("49E" . (S (NP (NPL Clinical history) (PP of (NPL gastrointestinal))) (VP disorders (SBAR that (SS (VP may (VP impair (NPL absorption))))))))
("50A" . (S (ADJP Regular) (NP (NPL use) (PP of (NPL oral steroids)))))
("51A" . (S (NPL Cigarette smoking)))
("51B" . (S (NPL nicotine replacement) (VP use)))
("52A" . (S (NP (NPL Regular intake) (PP of (NPL alcoholic))) (VP drinks (NPL >= 2/day))))
("53A" . (S (NPL Illicit drug) (VP use)))
("54A" . (S (SS (NP (NPL History) (PP of (NPL a psychological illness))))))
("55A" . (S (NP (NPL Dietary supplements) (VP containing (NPL phenolic))) (VP compounds (NPL one month) (PP (ADVP prior) to (NPL study admission)))))
("55B" . (S (NP (NPL herbal preparations) (VP containing (NPL phenolic))) (VP compounds (NPL one month) (PP (ADVP prior) to (NPL study admission)))))
("55C" . (S (NPL berry) (VP containing (SS (NPL preparations one month) (ADJP prior (PP to (NPL study admission)))))))
("55D" . (S (NPL cranberry) (VP capsules (NP (NPL one month) (ADJP prior (PP to (NPL study admission)))))))
("56A" . (S (NP (NPL Treatment) (PP with (NP (NPL (NNPX Vitamin E)) (PP within (NP (NPL 1 month) (PP of (NP (NPL enrollment) EXCLUDING vitamin E))))))) (VP dose (NPL (CD <= 2 *) RDA))))
("56B" . (S (NP (NPL Treatment) (PP with (NP (NPL (NNPX Vitamin C)) (PP within (NP (NPL 1 month) (PP of (NPL enrollment EXCLUDING vitamin C))))))) (VP dose (NPL (CD <= 2 *) RDA))))
("56C" . (S (NPL Treatment) (PP with (NP (NPL beta) (PP carotene within (NP (NPL 1 month) (PP of (NPL enrollment))))))))
("56D" . (S (NP (NPL Treatment) (PP with (NPL lipoic))) (VP acid (PP within (NP (NPL 1 month) (PP of (NPL enrollment)))))))
("56E" . (S (NP (NPL Treatment) (PP with (NPL other food))) (VP supplements (PP within (NP (NPL 1 month) (PP of (NPL enrollment)))))))
("56F" . (S (NP (NPL Treatment) (PP with (ADJP herbal))) (VP supplements (PP within (NP (NPL 1 month) (PP of (NPL enrollment)))))))
))
(defun id2nyu (id) (assoc (string-upcase id) *nyu* :test #'equal))  ;nyu just in case

