;(in-package "LISA") ;(in-package "LISA-USER")
;==> fl-2e.cl <==
;(mapcar #'print *fl2e*)
(defvar *fl-2e* ;cleaned up version
 '( ;only the NP this time
("1A". "adult")
("1B". "age")
("1C". "age")
("2A". "heart disease")
("2B". "risk factors")
("3A". "dyslipidemia")
("3B". "dyslipidemia treatment")
("4A". "stable")
("5A" . "exposure to cholesteryl-ester transfer protein inhibitor")
("5B" . "exposure to cholesteryl-ester transfer protein vaccine")
("6A". "coronary events") ;put s back in
("6B". "ischemic attacks") ;put s back in
("6C". "cerebrovascular accident")
("7A". "anemia")
("8A". "hypertension")
("9A". "diabetes")
("10A". "age")
("11A". "women")
("11B". "postmenopausal")
("11C". "women")
("11D". "method for avoidance of pregnancy")
("12A". "statin therapy")
("13A". "heart disease")
("14A". "age")
("14B". "Diabetes")
("14C". "cholesterol")
("14D". "smoker")
("14E". "stopped smoking")
("14F". "kidney function")
("14G". "kidney function")
("14H". "artery disease")
("14I". "stroke")
("14J". "arterial disease")
("15A". "revascularizarion")
("15B". "stent placement")
("15C". "bypass")
("15D". "surgical procedure")
("16A". "Liver disease")
("17A". "kidney function")
("17B". "removal of a kidney")
("17C". "transplant")
("18A". "heart failure")
("19A". "blood pressure")
("19B". "lifestyle changes")
("19C" . "medications")
("20A". "life-threatening disease") ; EXCLUDING heart disease
("20B". "life expectancy")
("21A". "asthma")
("21B". "asthma")
("21C". "medication")
("22A". "pregnant")
("23A". "allergic response")
("23B". "allergic response")
("23C". "allergic response")
("24A". "abuse")
("24B". "abuse")
("24C". "mental impairment")
("24D". "psychological impairment")
("25A". "heart disease")
("26A". "angina pectoris")
("27A". "heart disease")
("27B". "angiography")
("27C". "heart disease")
("27D". "exercise stress testing")
("28A". "smokers") ;put s back in
("29A". "arrhythmia")
("30A" . "heart disease")
("30B". "main stem stenosis")
("31A". "conduction abnormality")
("32A". "digoxin therapy")
("33A". "hypertension")
("34A". "Renal failure")
("35A". "Hepatic failure")
("36A". "coronary syndrome")
("36B". "anginal symptoms")
("37A" . "exposure to air pollution")
("38A". "artery disease")
("39A". "men")
("39B". "women")
("39C". "postmenopausal")
("40A". "age")
("40B". "age")
("41A". "weight")
("41B". "body mass index")
("41C". "body mass index")
("42A". "artery disease")
("42B". "coronary angiography")
("42C". "artery disease")
("42D" . "infarction")
("42E". "artery disease")
("42F". "stress test")
("43A". "stent procedure")
("43B". "stent procedure")
("44A". "English language")
("45A". "heart failure")
("46A". "allergy")
("46B". "allergy")
("47A" . "pregnancy test")
("47B". "lactating")
("47C". "pregnancy")
("48A". "consumption of nuts")
("49A" . "major illness")
("49B" . "cancer")
("49C" . "renal failure")
("49D" . "hepatic failure")
("49E" . "gastrointestinal disorders")
("50A". "use of oral steroids")
("51A". "smoker")
("51B". "nicotine replacement")
("52A". "intake of alcoholic drinks")
("53A". "drug use")
("54A". "psychological illness")
("55A". "dietary supplements")
("55B". "herbal preparations")
("55C". "berry containing preparations")
("55D". "capsules")
("56A" . "treatment with Vitamin E") ; EXCLUDING vitamin E dose
("56B" . "treatment with Vitamin C") ; EXCLUDING vitamin E dose
("56C". "treatment with beta carotene")
("56D". "treatment with lipoic acid")
("56E". "treatment with food supplements")
("56F". "treatment with herbal supplements")
))

;==> fl-2em.cl <==
(defvar *fl-2em* '(
("2A" . "coronary")
("2B" . "coronary [modifier] heart disease")
("3B" . "appropriate")
("5A" . "previous")
("5B" . "previous")
("6A" . "significant")
("6B" . "transient")
("7A" . "severe")
("8A" . "uncontrolled")
("9A" . "poorly controlled")
("11D" . "highly effective")
("12A" . "current")
("13A" . "chronic [modifier] coronary")
("14B" . "requiring treatment with medication")
("14C" . "low [modifier] HDL")
("14D" . "current [modifier] cigarettes")
("14F" . "mild [modifier] reduction in")
("14G" . "moderate [modifier] reduction in")
("14H" . "carotid")
("14I" . "ischemic")
("14J" . "peripheral")
("15A" . "planned [modifier] coronary")
("15B" . "planned")
("15C" . "planned [modifier] heart")
("15D" . "planned [modifier] major")
("17A" . "severe [modifier] reduction in")
("17C" . "kidney")
("18A" . "severe")
("19A" . "higher than normal") 
("19B" . "anti-hypertensive")
;;("19C" . "anti-hypertensive)  ;[modifier]  treatment with [NP" ;check on 
("19C" . "(anti-hypertensive [modifier] medications [NP]) ") ;[modifier]  treatment with [NP]
;("19C" . "anti-hypertensive") ;[modifier]  treatment with [NP]
("21A" . "Severe")
("21B" . "poorly controlled")
("21C" . "asthma")
("23A" . "severe [modifier] to food [modifier") 
("23B" . "severe [modifier] to drink [modifier") 
("23C" . "severe [modifier] to insect stings [modifier") 
("24A" . "drug")
("24B" . "alcohol")
("25A" . "stable")
("26A" . "symptomatic")
("27A" . "coronary")
("27C" . "coronary")
("28A" . "current")
("29A" . "history of [contextual modifier]") 
("30A" . "severe [modifier] 3-vessel [modifier]")
("30B" . "left [modifier]  not revascularised [modifier") 
("31A" . "resting")
("33A" . "uncontrolled")
("36A" . "Acute")
("36B" . "unstable")
("37A" . "significant [modifier] occupation")
("38A" . "stable [modifier] coronary")
("42A" . "coronary")
("42B" . "lesions on")
("42C" . "coronary")
("42D" . "history of [contextual modifier]  myocardial")
("42E" . "coronary")
("42F" . "positive")
("43B" . "stable [modifier] after [context modifier]") 
("46A" . "history of [contextual modifier] to nuts [modifier") 
("46B" . "known [modifier]  to nuts [modifier") 
("47A" . "positive [modifier] urine [modifier] beta HCG [modifier] ") 
("47C" . "planned")
("48A" . "regular")
("49A" . "clinical [modifier] history of [contextual modifier] ") 
("49B" . "clinical [modifier] history of [contextual modifier] end-stage [modifier") 
("49C" . "clinical [modifier] history of [contextual modifier] ") 
("49D" . "clinical [modifier] history of [contextual modifier] ") 
("49E" . "clinical [modifier] history of [contextual modifier]  absorption-impairing [modifier") 
("50A" . "regular")
("51A" . "Cigarette")
("52A" . "regular")
("53A" . "illicit")
("54A" . "history of [contextual modifier]") 
("55A" . "containing phenolic compounds")
("55B" . "containing phenolic compounds")
("55D" . "cranberry")
))
