(defvar *cea* '(
 (31 . "Resting_DORA/JJ/1 conduction_ORTF/NN/2 abnormality_CGAB/NN/3 ././-1 \nResting_DORA/JJ/2/1 conduction_ORTF/NN/4/2 abnormality_CGAB/NN/2/3 null/./0/-1")
 (32 . "Digoxin_PHSU/NNP/1 therapy_TOPP/NN/2 ././-1 \nDigoxin_PHSU/NNP/2/1 therapy_TOPP/NN/3/2 null/./0/-1")
 (33 . "uncontrolled_QLCO/VBN/1 hypertension_DSYN/NN/2 ././-1 \nuncontrolled_QLCO/VBN/2/1 hypertension_DSYN/NN/3/2 null/./0/-1")
 (34 . "Renal_failure_DSYN/NN/1 ././-1 \nRenal_failure_DSYN/NN/2/1 null/./0/-1")
 (35 . "Hepatic_failure_DSYN/NN/1 ././-1 \nHepatic_failure_DSYN/NN/2/1 null/./0/-1")
 (36 . "Acute_coronary_syndrome_DSYN/NN/7 or/CC/0 unstable_PHPR/JJ/3 symptoms_SOSY/NN/1 within/IN/3 3/CD/6 months_TMCO/NN/4 ././-1 \nAcute_coronary_syndrome_DSYN/NN/2/4 unstable_PHPR/JJ/2/2 symptoms_SOSY/NN/3/0 months_TMCO/NN/2/2 null/./0/-1")
 (37 . "Significant_QLCO/JJ/2 occupation_OCDI/JJ/2 exposure_CLNA/NN/5 to/IN/2 air_pollution_EEHU/NN/3 ././-1 \nSignificant_QLCO/JJ/2/2 occupation_OCDI/JJ/2/2 exposure_CLNA/NN/3/4 air_pollution_EEHU/NN/3/2 null/./0/-1")
 (38 . "Stable_QLCO/JJ/2 CAD_TOPP/JJ/2 Patients_ORGM/NN/13/LRB/2 men_ANTB/NN/3 &/CC/4 postmenopausal_TMCO/JJ/7 women_POPG/NN/5 )/RRB/4 NIL_QNCO/JJ/10 aged_ORGF/NN/8 2080/CD/10 years_TMCO/NN/10 ././-1 \nStable_QLCO/JJ/2/2 CAD_TOPP/JJ/2/2 Patients_ORGM/NN/3/9 men_ANTB/NN/2/2 postmenopausal_TMCO/JJ/4/5 women_POPG/NN/2/3 NIL_QNCO/JJ/2/7 aged_ORGF/NN/5/3 years_TMCO/NN/2/7 null/./0/-1")
 (39 . "rest in 38")
 (40 . "defn: adult from before")
 (41 . "weighing_DIAP/VBG/11 less_QLCO/JJ/11 than/IN/1 115/CD/4 Kg_QNCO/NN/2/LRB/2 BMI_CLNA/JJ/7 range_QNCO/NN/8 18535/NN/5 m2/CD/8 )/RRB/9 ././-1 \nweighing_DIAP/VBG/2/5 less_QLCO/JJ/8/5 Kg_QNCO/NN/2/1 BMI_CLNA/JJ/2/4 range_QNCO/NN/4/1 null/./0/-1")
 (42 . "with/IN/18 coronary_artery_disease_DSYN/NN/0 defined_CNCE/VBN/0 by/IN/2 the/DT/2 presence_TOPP/NN/2 of/IN/5 lesions_INPR/NN/6 on/IN/7 coronary_angiography_DIAP/NN/8 ,/CC/9 history_ORGA/NN/10 of/IN/11 myocardial_infarction_DSYN/NN/12 ,/CC/13 or/CC/14 positive_QLCO/JJ/17 stress_test_DIAP/NN/15 ././-1 \ncoronary_artery_disease_DSYN/NN/3/9 defined_CNCE/VBN/13/9 presence_TOPP/NN/2/1 lesions_INPR/NN/3/2 coronary_angiography_DIAP/NN/3/3 history_ORGA/NN/6/4 myocardial_infarction_DSYN/NN/3/5 positive_QLCO/JJ/2/8 stress_test_DIAP/NN/3/6 null/./0/-1")
 (43 . "Subjects_HUMN/NN/1 are/VBT/22 eligible_IDCN/JJ/1 to/IN/2 participate_FTCN/NN/3 after/IN/4 a/DT/8 stent_MEDD/NN/8 procedure_TOPP/NN/5 only/RB/12 after/IN/5 they/PRP/5 have/VB/11 been_HOPS/VBN/12 stable_QLCO/JJ/22 for/IN/14 one/CD/17 month_TMCO/NN/15 after/IN/17 the/DT/21 stent_MEDD/NN/21 procedure_TOPP/NN/18 ././-1 \nSubjects_HUMN/NN/2/10 eligible_IDCN/JJ/4/10 participate_FTCN/NN/3/1 stent_MEDD/NN/4/4 procedure_TOPP/NN/2/2 been_HOPS/VBN/10/2 stable_QLCO/JJ/8/10 month_TMCO/NN/2/6 stent_MEDD/NN/4/9 procedure_TOPP/NN/2/7 null/./0/-1")
 (44 . "Languages_LANG/NN/3 :/&/0 English_POPG/NN/1 ././-1 \nLanguages_LANG/NN/2/2 English_POPG/NN/2/0 null/./0/-1")
 (45 . "Subjects_HUMN/NN/11 with/IN/0 heart_failure_DSYN/NN/1 are/VBT/11 not/RB/5 eligible_IDCN/JJ/3 for/IN/5 participation_FTCN/NN/6 in/IN/7 this/DT/10 study_LBPR/NN/8 ././-1 \nSubjects_HUMN/NN/2/5 heart_failure_DSYN/NN/3/0 eligible_IDCN/JJ/6/5 participation_FTCN/NN/3/2 study_LBPR/NN/2/3 null/./0/-1")
 (46 . "History_ORGA/NN/9 or/CC/0 known_QLCO/VBN/3 allergy_PATF/NN/1 to/IN/3 nuts_MEDD/NN/4 of/IN/5 any/DT/8 kind_QLCO/NN/6 ././-1 \nHistory_ORGA/NN/2/5 known_QLCO/VBN/2/2 allergy_PATF/NN/3/0 nuts_MEDD/NN/3/2 kind_QLCO/NN/2/3 null/./0/-1")
 (47 . "Women_POPG/NN/18 with/IN/0 a/DT/4 positive_QLCO/JJ/4 urine_BDSU/NN/1 beta_HCG_HORM/JJ/4 pregnancy_test_LBPR/NN/4 and/CC/6 lactating_PHSU/JJ/9 women_POPG/NN/7 or/CC/9 women_POPG/NN/10 who/WPS/11 are/VBT/12 planning_FTCN/NN/13 to/IN/14 become/NN/17 pregnant_FNDG/NN/15 ././-1 \nWomen_POPG/NN/2/10 positive_QLCO/JJ/4/2 urine_BDSU/NN/2/0 beta_HCG_HORM/JJ/6/2 pregnancy_test_LBPR/NN/4/2 lactating_PHSU/JJ/2/6 women_POPG/NN/3/4 women_POPG/NN/4/6 planning_FTCN/NN/10/7 pregnant_FNDG/NN/2/8 null/./0/-1")
 (48 . "Regular_QLCO/JJ/1 consumption_ACTY/NN/14 of/IN/1 >=/OP/1 5/CD/2 oz_QNCO/NN/4 nuts/CC/5 for/IN/3 6/CD/9 weeks_TMCO/NN/7 prior_TMCO/JJ/9 to/IN/10 study_LBPR/NN/13 admission_HLCA/NN/11 ././-1 \nRegular_QLCO/JJ/2/1 consumption_ACTY/NN/3/7 oz_QNCO/NN/2/1 weeks_TMCO/NN/2/1 prior_TMCO/JJ/2/3 study_LBPR/NN/4/6 admission_HLCA/NN/2/4 null/./0/-1")
 (49 . "Clinical_QLCO/JJ/1 history_ORGA/NN/34 of/IN/1 other_QLCO/JJ/5 major_QLCO/JJ/5 illness_FNDG/NN/2 including_FTCN/VBG/2 end_stage_cancer/NN/6 ,/CC/7 renal_failure_DSYN/NN/8 ,/CC/9 hepatic_failure_DSYN/NN/10 ,/CC/11 gastrointestinal_disorders_DSYN/NN/12 that/WPS/13 may/VBT/14 impair_FNDG/JJ/15 absorption_NPOP/NN/15 ,/CC/17 or/CC/18 other_QLCO/JJ/21 conditions_QLCO/NN/19 that/WPS/21 in/IN/21 the/DT/25 opinion/NN/23 of/IN/25 the/DT/28 principal_QLCO/NN/26 investigator/VBT/34 make/VB/29 a/DT/33 clinical_study_RESA/NN/33 inappropriate_QLCO/NN/30 ././-1 \nClinical_QLCO/JJ/2/1 history_ORGA/NN/3/16 other_QLCO/JJ/5/4 major_QLCO/JJ/4/4 illness_FNDG/NN/2/1 including_FTCN/VBG/4/1 renal_failure_DSYN/NN/2/5 hepatic_failure_DSYN/NN/2/6 gastrointestinal_disorders_DSYN/NN/2/7 impair_FNDG/JJ/14/8 absorption_NPOP/NN/12/8 other_QLCO/JJ/2/12 conditions_QLCO/NN/3/10 principal_QLCO/NN/2/12 clinical_study_RESA/NN/4/15 inappropriate_QLCO/NN/2/16 null/./0/-1")
 (50 . "Regular_QLCO/NN/1 use_INPR/NN/5 of/IN/1 oral_BSOJ/JJ/4 steroids_STRD/NN/2 ././-1 \nRegular_QLCO/NN/2/1 use_INPR/NN/3/4 oral_BSOJ/JJ/4/3 steroids_STRD/NN/2/1 null/./0/-1")
 (51 . "Cigarette_smoking_INBE/NN/6 and/CC/0 slash/NN/1 or/CC/2 nicotine_replacement_TOPP/NN/5 use_INPR/NN/3 ././-1 \nCigarette_smoking_INBE/NN/2/3 nicotine_replacement_TOPP/NN/2/2 use_INPR/NN/3/0 null/./0/-1")
 (52 . "Regular_QLCO/JJ/2 daily_TMCO/JJ/2 intake_FTCN/NN/8 of/IN/2 >=/OP/2 2/CD/3 alcoholic_PODG/NN/5 drinks/VBT/8 ././-1 \nRegular_QLCO/JJ/2/2 daily_TMCO/JJ/2/2 intake_FTCN/NN/3/4 alcoholic_PODG/NN/2/2 null/./0/-1")
 (53 . "Illicit_drug_use_INBE/NN/1 ././-1 \nIllicit_drug_use_INBE/NN/2/1 null/./0/-1")
 (54 . "History_ORGA/NN/23 of/IN/0 a/DT/4 psychological_MOBD/JJ/4 illness_FNDG/NN/1 or/CC/4 condition_QLCO/NN/5 such/JJ/6 as/PIN/9 to/IN/7 interfere_QLCO/NN/9 with/IN/10 the/DT/13 subject_HUMN/NN/14 's/POS/15 ability_ORGA/NN/11 to/TO/11 understand/VB/16 the/DT/19 requirements_IDCN/NN/17 of/IN/19 the/DT/22 study_LBPR/NN/20 ././-1 \nHistory_ORGA/NN/2/9 psychological_MOBD/JJ/4/2 illness_FNDG/NN/2/0 condition_QLCO/NN/2/2 interfere_QLCO/NN/2/3 subject_HUMN/NN/4/6 ability_ORGA/NN/4/4 requirements_IDCN/NN/3/4 study_LBPR/NN/2/7 null/./0/-1")
 (55 . "No_GEOA/NN/27 dietary_supplements_FOOD/NN/0 containing_FTCN/JJ/1 phenolic_PHSU/NN/4 compounds_CHEM/NN/1 ,/CC/4 i.e./NN/5 ,/CC/6 herbal_preparations_PHSU/NN/7 ,/CC/8 or/CC/9 berry_FOOD/JJ/12 containing_FTCN/NN/13 preparations_HLCA/NN/10/LRB/13 such/JJ/14 as/IN/15 cranberry_FOOD/JJ/18 capsules_BODM/NN/16 )/RRB/16 for/IN/19 one/CD/22 month_TMCO/NN/20 prior_TMCO/JJ/22 to/IN/23 study_LBPR/NN/26 admission_HLCA/NN/24 ././-1 \nNo_GEOA/NN/2/15 dietary_supplements_FOOD/NN/2/0 containing_FTCN/JJ/5/1 phenolic_PHSU/NN/4/4 compounds_CHEM/NN/2/1 herbal_preparations_PHSU/NN/2/4 berry_FOOD/JJ/2/7 containing_FTCN/NN/4/8 preparations_HLCA/NN/2/5 cranberry_FOOD/JJ/4/10 capsules_BODM/NN/2/8 month_TMCO/NN/2/8 prior_TMCO/JJ/16/11 study_LBPR/NN/4/14 admission_HLCA/NN/2/12 null/./0/-1")
 (56 . "Treatment_TOPP/NN/47 with/IN/0 Vitamin_E_PHSU/NN/1 ,/CC/2 Vitamin_C_PHSU/NNP/3 ,/CC/4 beta_carotene_PHSU/NN/5 ,/CC/6 lipoic_acid_PHSU/NN/7 ,/CC/8 or/CC/9 other_QLCO/JJ/12 food_FOOD/NN/10 or/CC/12 herbal_INPR/JJ/15 supplements_FTCN/NN/13 within/IN/15 1/CD/18 month_TMCO/NN/16 of/IN/18 enrollment_HLCA/NN/19/LRB/19 subjects_HUMN/JJ/21 taking_ACTY/VBG/0 multivitamins_PHSU/NN/23 or/CC/24 other_QLCO/JJ/27 forms_BODM/NN/25 of/IN/27 vitamin_E_PHSU/NN/28 and/CC/29 C_HOPS/NN/30 in/IN/31 doses_PHSU/NN/32 that/SCON/47 do/VB/34 not/RB/37 exceed/VB/32 two_QNCO/NN/37 times/CC/38 the/DT/41 RDA_MBRT/NN/42 will/VBT/47 not/RB/45 be/VB/42 excluded_FTCN/VBN/44 )/RRB/45 ././-1 \nTreatment_TOPP/NN/2/22 Vitamin_E_PHSU/NN/3/0 Vitamin_C_PHSU/NNP/2/1 beta_carotene_PHSU/NN/2/2 lipoic_acid_PHSU/NN/2/3 other_QLCO/JJ/2/6 food_FOOD/NN/3/4 herbal_INPR/JJ/2/8 supplements_FTCN/NN/3/6 month_TMCO/NN/2/8 enrollment_HLCA/NN/3/9 subjects_HUMN/JJ/18/9 taking_ACTY/VBG/16/0 multivitamins_PHSU/NN/20/12 other_QLCO/JJ/2/15 forms_BODM/NN/3/13 vitamin_E_PHSU/NN/3/15 C_HOPS/NN/22/16 doses_PHSU/NN/3/17 two_QNCO/NN/28/17 RDA_MBRT/NN/3/22 excluded_FTCN/VBN/34/22 null/./0/-1")
 (17 . "Severe_QLCO/JJ/1 reduction_NPOP/NN/11 in/IN/1 kidney_function_ORTF/NN/2 OR_PHSU/NN/2 removal_TOPP/NN/1 of/IN/5 a/DT/5 kidney_BPOC/NN/9 OR_PHSU/NN/10 kidney_transplant_TOPP/NN/5 ././-1 \nSevere_QLCO/JJ/2/1 reduction_NPOP/NN/3/8 kidney_function_ORTF/NN/3/1 OR_PHSU/NN/4/1 removal_TOPP/NN/2/1 kidney_BPOC/NN/4/6 OR_PHSU/NN/8/7 kidney_transplant_TOPP/NN/2/4 null/./0/-1")
 (1 . "adult_AGGP/NN/1 patients_ORGM/NN/7 ,/CC/1 1875/NN/4 years_TMCO/NN/2 of/IN/4 age_ORGF/NN/5 ././-1 \nadult_AGGP/NN/2/1 patients_ORGM/NN/3/4 years_TMCO/NN/3/1 age_ORGF/NN/3/2 null/./0/-1")
 (2 . "CHD_TOPP/NN/8 ,/CC/0 including_FTCN/VBG/1 patients_ORGM/NN/2 with/IN/3 other_QLCO/JJ/7 CHD_TOPP/JJ/7 risk_factors_QNCO/NN/4 ././-1 \nCHD_TOPP/NN/2/6 including_FTCN/VBG/4/0 patients_ORGM/NN/2/1 other_QLCO/JJ/5/5 CHD_TOPP/JJ/4/5 risk_factors_QNCO/NN/2/2 null/./0/-1")
 (3 . "treated_TOPP/VBN/4 appropriately/RB/0 for/IN/4 dyslipidemia_DSYN/NN/2 ././-1 \ntreated_TOPP/VBN/2/2 dyslipidemia_DSYN/NN/3/2 null/./0/-1")
 (4 . "clinically/RB/1 stable_QLCO/JJ/2 ././-1 \nstable_QLCO/JJ/3/1 null/./0/-1")
 (5 . "previous_TMCO/JJ/1 exposure_CLNA/NN/8 to/IN/1 any/DT/5 CETP_BACS/JJ/5 inhibitor_PHSU/NN/2 or/CC/5 vaccine_PHSU/NN/6 ././-1 \nprevious_TMCO/JJ/2/1 exposure_CLNA/NN/3/5 CETP_BACS/JJ/4/3 inhibitor_PHSU/NN/2/1 vaccine_PHSU/NN/2/3 null/./0/-1")
 (6 . "recent_TMCO/NN/14/LRB/0 within/IN/1 3/CD/4 months_TMCO/NN/2 )/RRB/1 clinically/RB/7 significant_QLCO/JJ/9 coronary_BPOC/JJ/9 events_EVNT/NN/14 ,/CC/9 transient_ischemic_attacks_DSYN/NN/10 or/CC/11 cerebrovascular_accident_DSYN/NN/12 ././-1 \nrecent_TMCO/NN/2/7 months_TMCO/NN/2/0 significant_QLCO/JJ/4/4 coronary_BPOC/JJ/2/4 events_EVNT/NN/3/7 transient_ischemic_attacks_DSYN/NN/2/4 cerebrovascular_accident_DSYN/NN/2/5 null/./0/-1")
 (7 . "severe_QLCO/JJ/1 anemia_DSYN/NN/2 ././-1 \nsevere_QLCO/JJ/2/1 anemia_DSYN/NN/3/2 null/./0/-1")
 (8 . "uncontrolled_QLCO/VBN/1 hypertension_DSYN/NN/2 ././-1 \nuncontrolled_QLCO/VBN/2/1 hypertension_DSYN/NN/3/2 null/./0/-1")
 (9 . "poorly/RB/1 controlled_PHSU/VBN/3 diabetes_DSYN/NN/3 ././-1 \ncontrolled_PHSU/VBN/4/2 diabetes_DSYN/NN/2/2 null/./0/-1")
 (10 . "Men_ANTB/NN/23 or/CC/0 women_POPG/NN/1 >=/OP/4 18/CD/5 years_TMCO/NN/2 old_TMCO/JJ/5 ././17 Women_POPG/NN/6 must/VBT/0 be/VB/0 post/IN/2 menopausal_PFUN/JJ/2 or/CC/0 using_INPR/VBG/0 a_HOPS/NN/10 highly/RB/13 effective_QLCO/JJ/14 method_INPR/NN/0 for/IN/18 avoidance_MENP/NN/0 of/IN/20 pregnancy_ORGF/NN/0 ././-1 \nMen_ANTB/NN/2/13 women_POPG/NN/4/0 years_TMCO/NN/4/1 old_TMCO/JJ/2/2 null/./6/17 Women_POPG/NN/4/6 menopausal_PFUN/JJ/3/2 using_INPR/VBG/12/0 a_HOPS/NN/10/10 effective_QLCO/JJ/12/14 method_INPR/NN/16/0 avoidance_MENP/NN/3/0 pregnancy_ORGF/NN/3/0 null/./0/-1")
 (11 . "NIL_QNCO/NN/1 ././-1 \nNIL_QNCO/NN/2/1 null/./0/-1")
 (12 . "Current_TMCO/JJ/1 treatment_TOPP/NN/17 with/IN/1 statin_PHSU/JJ/4 therapy_TOPP/NN/2 unless/NN/2 the/DT/7 study_LBPR/NN/11 doctor_PROG/NN/9 determines_QLCO/NN/10 statins_PHSU/NN/7 are/VBT/17 not/RB/13 appropriate_QLCO/JJ/11 for/IN/13 the/DT/16 subject_HUMN/NN/14 ././-1 \nCurrent_TMCO/JJ/2/1 treatment_TOPP/NN/3/10 statin_PHSU/JJ/4/3 therapy_TOPP/NN/2/1 study_LBPR/NN/6/10 doctor_PROG/NN/4/6 determines_QLCO/NN/2/7 statins_PHSU/NN/4/4 appropriate_QLCO/JJ/8/10 subject_HUMN/NN/2/8 null/./0/-1")
 (13 . "Chronic_TMCO/JJ/1 coronary_heart_disease_DSYN/NN/2 ././-1 \nChronic_TMCO/JJ/2/1 coronary_heart_disease_DSYN/NN/3/2 null/./0/-1")
 (14 . "At/IN/60 least/NN/0 one/CD/1 of/IN/0 the/DT/5 following_TMCO/VBG/0 :/&/5 >=/OP/8 60/CD/9 years_TMCO/NN/6 old_TMCO/JJ/9 ;/CC/9 Diabetes_DSYN/NN/11 requiring_FTCN/VBG/12 treatment_TOPP/NN/13 with/IN/14 medication_PHSU/NN/15 ;/CC/16 Low_HDL/NN/19 cholesterol_BACS/NN/17/LRB/19 \\good_QLCO/JJ/22 cholesterol\\_BACS/NN/20 )/RRB/22 Currently_TMCO/JJ/25 smoke_INBE/NN/26 cigarettes_MNOB/NN/23 or/CC/26 stopped_ACTY/VBN/27 smoking_INBE/VBG/27 within/IN/29 the/DT/34 past_TMCO/JJ/33 3/CD/34 months_TMCO/NN/30 ;/CC/34 Diagnosed_FNDG/NN/35 mild_QLCO/JJ/36 or/CC/36 moderate_QLCO/JJ/40 reduction_NPOP/NN/38 in/IN/40 kidney_function_ORTF/NN/41 ;/CC/42 Cerebrovascular_disease_PATF/NN/43 (/LRB/44 carotid_artery_disease_DSYN/NN/44 or/CC/46 ischemic_stroke_DSYN/NN/47 more_FTCN/JJ/48 than/IN/49 3/CD/52 months_TMCO/NN/50 prior_TMCO/JJ/52 to/IN/53 study_LBPR/NN/56 entry_FTCN/NN/54 )/RRB/54 OR_PHSU/NN/59 peripheral_arterial_disease_DSYN/NN/60 ././-1 \nfollowing_TMCO/VBG/2/32 years_TMCO/NN/4/0 old_TMCO/JJ/2/1 Diabetes_DSYN/NN/4/1 requiring_FTCN/VBG/8/3 treatment_TOPP/NN/6/4 medication_PHSU/NN/3/5 cholesterol_BACS/NN/3/6 \\good_QLCO/JJ/14/9 cholesterol\\_BACS/NN/12/7 Currently_TMCO/JJ/5/11 smoke_INBE/NN/4/12 cigarettes_MNOB/NN/2/9 stopped_ACTY/VBN/16/12 smoking_INBE/VBG/20/12 past_TMCO/JJ/4/16 months_TMCO/NN/4/14 Diagnosed_FNDG/NN/2/16 mild_QLCO/JJ/3/17 moderate_QLCO/JJ/2/20 reduction_NPOP/NN/3/17 kidney_function_ORTF/NN/3/20 Cerebrovascular_disease_PATF/NN/2/21 carotid_artery_disease_DSYN/NN/2/22 ischemic_stroke_DSYN/NN/2/23 more_FTCN/JJ/30/24 months_TMCO/NN/2/25 prior_TMCO/JJ/32/26 study_LBPR/NN/4/29 entry_FTCN/NN/2/27 OR_PHSU/NN/2/31 peripheral_arterial_disease_DSYN/NN/3/32 null/./0/-1")
 (15 . "Planned_FTCN/VBN/14 coronary_revascularization/NN/14/LRB/1 such/JJ/2 as/IN/3 stent_placement_TOPP/NN/4 or/CC/5 heart_bypass_TOPP/NN/6 )/RRB/7 or/CC/8 any/DT/13 other_QLCO/JJ/13 major_QLCO/JJ/13 surgical_procedure_TOPP/NN/8 ././-1 \nPlanned_FTCN/VBN/2/6 stent_placement_TOPP/NN/3/6 heart_bypass_TOPP/NN/2/1 other_QLCO/JJ/5/5 major_QLCO/JJ/4/5 surgical_procedure_TOPP/NN/2/2 null/./0/-1")
 (18 . "Severe_QLCO/JJ/1 heart_failure_DSYN/NN/2 ././-1 \nSevere_QLCO/JJ/2/1 heart_failure_DSYN/NN/3/2 null/./0/-1")
 (19 . "Blood_pressure_DIAP/NN/10 higher_QNCO/JJ/0 than/IN/1 normal_FNDG/JJ/1 despite/IN/3 lifestyle_changes/NN/4 and/CC/5 treatment_TOPP/NN/6 with/IN/7 medications_PHSU/NN/8 ././-1 \nBlood_pressure_DIAP/NN/2/5 higher_QNCO/JJ/8/0 normal_FNDG/JJ/3/1 treatment_TOPP/NN/4/2 medications_PHSU/NN/3/3 null/./0/-1")
 (20 . "Any_IDCN/JJ/2 life_threatening_FNDG/VBG/2 disease_DSYN/NN/3 expected_IDCN/NN/18 to/IN/3 result_FTCN/NN/4 in/IN/5 death_ORGF/NN/6 within/IN/7 the/DT/12 next_SPCO/JJ/11 2/CD/12 years_TMCO/NN/8/LRB/8 other_QLCO/JJ/13 than/IN/14 heart_disease_DSYN/NN/15 )/RRB/15 ././-1 \nAny_IDCN/JJ/2/2 life_threatening_FNDG/VBG/4/2 disease_DSYN/NN/2/3 expected_IDCN/NN/10/10 result_FTCN/NN/3/3 death_ORGF/NN/3/4 next_SPCO/JJ/4/7 years_TMCO/NN/4/5 other_QLCO/JJ/8/5 heart_disease_DSYN/NN/3/8 null/./0/-1")
 (21 . "Severe_asthma_FNDG/NN/7 that/WPS/0 is/VBT/1 poorly/RB/4 controlled_PHSU/VBN/2 with/IN/4 medication_PHSU/NN/5 ././-1 \nSevere_asthma_FNDG/NN/2/3 controlled_PHSU/VBN/6/0 medication_PHSU/NN/3/1 null/./0/-1")
 (22 . "Pregnant_FNDG/JJ/1 Note_INPR/NN/17 :/&/1 A/DT/4 pregnancy_test_LBPR/NN/5 will/VBT/2 be/VB/5 performed_QLCO/VBN/6 on/IN/7 all/DT/12 non_GNGM/JJ/11 sterile_PATF/NN/12 women_POPG/NN/8 prior_TMCO/JJ/12 to/IN/13 study_LBPR/NN/16 entry_FTCN/NN/14 ././-1 \nPregnant_FNDG/JJ/2/1 Note_INPR/NN/3/10 pregnancy_test_LBPR/NN/3/1 performed_QLCO/VBN/4/1 non_GNGM/JJ/4/5 sterile_PATF/NN/2/6 women_POPG/NN/4/3 prior_TMCO/JJ/6/6 study_LBPR/NN/4/9 entry_FTCN/NN/2/7 null/./0/-1")
 (23 . "did not parse")
 (24 . "Drug_PHSU/NN/32 or/CC/0 alcohol_abuse_MOBD/NN/1 within/IN/2 the/DT/7 past_TMCO/JJ/6 6/CD/7 months_TMCO/NN/3 OR_PHSU/NN/3 mental/CC/8 that/WPS/9 may/VBT/10 prevent/VB/11 the/DT/14 subject_HUMN/NN/12 from/IN/14 complying/NN/15 with/IN/16 study_LBPR/NN/19 procedures_TOPP/NN/17 or/CC/19 understanding_FNDG/NN/20 the/DT/23 goal_IDCN/NN/21 and/CC/23 potential_QLCO/JJ/26 risks_QLCO/NN/24 of/IN/26 participating_FTCN/NN/27 in/IN/28 the/DT/31 study_LBPR/NN/29 ././-1 \nDrug_PHSU/NN/2/14 alcohol_abuse_MOBD/NN/2/0 past_TMCO/JJ/4/3 months_TMCO/NN/4/1 OR_PHSU/NN/6/1 subject_HUMN/NN/3/4 study_LBPR/NN/4/7 procedures_TOPP/NN/2/5 understanding_FNDG/NN/12/7 goal_IDCN/NN/14/8 potential_QLCO/JJ/2/11 risks_QLCO/NN/3/9 participating_FTCN/NN/3/11 study_LBPR/NN/2/12 null/./0/-1")
 (25 . "Stable_QLCO/JJ/1 coronary_heart_disease_DSYN/NN/2 ././-1 \nStable_QLCO/JJ/2/1 coronary_heart_disease_DSYN/NN/2/2 null/./0/-1")
 (26 . "Symptoms_SOSY/NN/3 of/IN/0 angina_pectoris_SOSY/NN/1 ././-1 \nSymptoms_SOSY/NN/2/2 angina_pectoris_SOSY/NN/3/0 null/./0/-1")
 (27 . "Evidence_FTCN/NN/10 of/IN/0 coronary_heart_disease_DSYN/NN/1 by/IN/2 angiography_DIAP/NN/3 or/CC/4 by/IN/3 exercise_DORA/NN/3 stress_FNDG/NN/9 testing_LBPR/NN/6 ././-1 \nEvidence_FTCN/NN/2/6 coronary_heart_disease_DSYN/NN/3/0 angiography_DIAP/NN/3/1 exercise_DORA/NN/5/1 stress_FNDG/NN/4/5 testing_LBPR/NN/2/1 null/./0/-1")
 (28 . "Current_TMCO/JJ/1 smokers_FNDG/NN/2 ././-1 \nCurrent_TMCO/JJ/2/1 smokers_FNDG/NN/3/2 null/./0/-1")
 (29 . "History_ORGA/NN/3 of/IN/0 arrhythmia_PATF/NN/1 ././-1 \nHistory_ORGA/NN/2/2 arrhythmia_PATF/NN/3/0 null/./0/-1")
 (30 . "Severe_QLCO/NN/12 3/CD/0 vessel_BPOC/NN/3 coronary_heart_disease_DSYN/NN/1 or/CC/3 left_main_stem_BPOC/NN/6 stenosis_PATF/NN/4 that/WPS/6 has/VBT/7 not/RB/10 been_HOPS/VBN/8 revascularised/VBN/8 ././-1 \nSevere_QLCO/NN/2/6 vessel_BPOC/NN/4/2 coronary_heart_disease_DSYN/NN/2/0 left_main_stem_BPOC/NN/2/4 stenosis_PATF/NN/3/2 been_HOPS/VBN/8/4 null/./0/-1")
 (16 . "Liver_disease_DSYN/NN/1 ././-1 \nLiver_disease_DSYN/NN/2/1 null/./0/-1")
 ))

;defun cea-parts (n)
; (mapcar #'(lambda (wl) (append (split-by_ (first-lv wl)) (rest-lv wl)))
;  (mapcar #'(lambda (wg) (split-by-slash wg)) (split (gvcrit n "cea")))))
(defun cea-parts (n)
  (mapcar #'(lambda (wl) (cons (split-by_ (first-lv wl)) (rest-lv wl)))
	  (mapcar #'(lambda (wg) (split-by-slash wg)) (split (gvcrit n "cea")))))
(defun cea2parts (n)
  (mapcar #'(lambda (wl) (cons (split-by_ (first-lv wl)) (rest-lv wl)))
	  (mapcar #'(lambda (wg) (split-by-slash wg)) (split (gvcrit n "cea2")))))

;(defun secondNNp (l) (eq (second l) 'NN)) 
(defun secondNNp (l) (when (fulll l) (equal (second l) "NN"))) 
(defun bestNPs (n) (collect-if #'secondNNp (cea2parts n)))
;under-pd-l used to mv from bestNPs first wrds lst to mk-cNN /finish
(defun mk-cNN (ws) (sv-cls ws "cNN")) ;columbia NP ins
;(defun bestNP_2cNN (l) "columbia bestNPs lst2 cNN ins" (mk-cNN (under-pd-l (first-lv l))))
(defun bestNP_2c (l) (clean4echo (under-pd-l (first-lv l))))
;(loop for i from 1 to 54 do (format t "~&~a:~a" i (mapcar- #'bestNP_2c (bestNPs i))))
(defun bestNP_2cNN (l) "columbia bestNPs lst2 cNN ins" (mk-cNN (bestNP_2c l)))
;(mapcar- #'bestNP_2cNN (bestNPs 1))
(defun bestNPs2cNN (n) "assert cNNs for a criteria" (mapcar- #'bestNP_2cNN (bestNPs n)))
;(loop for n from 1 to 54 do (bestNPs2cNN n))  ;(taxonomy '|cNN|)  ;next cmp2 (taxonomy '|NOUN_PHRASE|)

(defgeneric abbrev-cls (w))
(defmethod abbrev-cls ((ws string)) (rm-star (string-downcase ws)))
;(defmethod abbrev-cls ((w symbol)) (rm-star (string-downcase (symbol-name w)))) 
(defmethod abbrev-cls ((w symbol)) (abbrev-cls (symbol-name w)))
(defmethod abbrev-cls ((wl list)) (abbrev-cls (first-lv (flatten (last wl))))) 

;(loop for i from 1 to 54 do (format t "~&~a" (cea-parts i)))
(defun cmp-cw (cl)
  "cmp columbia parse(lst) w/my word ins parse"
 (when (fulll cl)
  (let* ((phr+sc (first-lv cl))
	 (phr (butlast phr+sc))
	 (sc (last_lv phr+sc))
	 (pos (second-lv cl)) ;will have2see if in full list of POS of my ins
	 (n (last_lv cl))
	 (phr_ (str-cat_l phr)) ;try show-cl &see what parts are useful for a cmp
	 (clp (show-cl phr_))
	 (ctc (abbrev-cls sc))
	 (otc (abbrev-cls clp))
	 (tui=p (if (equal ctc otc) "sameTUI" (format nil "~a_~a" ctc otc))) 
	 )
    (format t "~&~a~a,~a,~a:~a[~a]" phr sc pos n clp tui=p)
      tui=p)))
;(loop for i from 1 to 54 do (format t "~&~a" (cmp_cw i)))
(defun cmp_cw (n)
  "get the columbia list, and cmp each phrase"
  (mapcar #'cmp-cw (cea-parts n)))
;(loop for i from 1 to 54 do (format t "~&~a" (cmp-cw (cea-parts i)))
;in end show this early comparision, and that I got it up&running,&thoughts of use
; incl maybe merging on a lower than service level; like i'd like to do w/metamap
; i'd like to use kb/info from all of them while choices are still being made
;
; =make a copy of cdkmf, that uses this&metamap,&doesn't depend on interlinked dirs,&put up on kepes
